### ISSUE TITLE
Custom background colors with images

### ISSUE THREAD

**Issue by ertdfgcb** [derf/feh#125]
It would be nice to be able to set a custom background color when using feh to set the background image. Currently, you can only set it to white or black. For example:

> feh --bg-center image.jpg --image-bg #151515

I actually have this implemented in my fork, but I wanted to make sure other people wanted this feature before I submitted a pull request.

**Comment by r8b7xy** [comment]
Any progress in implementing this feature?

**Comment by ertdfgcb** [comment]
It's been done for nearly 2 years, I'm not sure why the author (of feh)
hasn't merged the pull request. I haven't heard anything from him, but here
<https://github.com/ertdfgcb/feh/tree/bg-image-color> is the branch the
codes on if you want to compile it yourself.

**Comment by ertdfgcb** [comment]
Also, here's the pull request: https://github.com/derf/feh/pull/126

**Comment by derf** [comment]
Sorry, while I meant to get back to feh for quite a while I never really did and worked on other projects instead.

At the moment, your code segfaults when setting a wallpaper without the -B / --image-bg option. However, I have merged it with master and commited to https://github.com/derf/feh/tree/ertdfgcb-bg-image-color for now. So there isn't that much left to do (and the chances for a proper merge into master are above zero at least :) )

**Comment by ertdfgcb** [comment]
Awesome, I'll look into that segfault, thanks for letting me know.

**Comment by AshenDrops** [comment]
It's important to note that using a value starting with a # in the command causes an error in creating the ~/.fehbg file, since it comments out anything past it.

**Comment by ikk00** [comment]
hi.
i would also like to extend this request to have ability to specify different color for full screen mode.
for viewing translucent images. switching full screen when background color changes would make identifying of transparent parts easier.
