### ISSUE TITLE
Key to toggle auto-zoom

### ISSUE THREAD

**Issue by cpoakes** [derf/feh#127]
This is a feature request.  The auto-zoom feature (-Z) can also be turned on and off from the menu.  It would be convenient if there was a key to toggle auto-zoom, much like the toggle_info or toggle_filenames keys which also have related menu items.

Contact me for a patch implementing "toggle_auto_zoom" as "Z" (capital zed).

**Comment by ulteq** [comment]
This can be closed: https://github.com/derf/feh/commit/d03fc61a268048e1bcef04fb00883c6cd339027b
