### ISSUE TITLE
adapt to changes in picture directory

### ISSUE THREAD

**Issue by camelreef** [derf/feh#141]
Hello,

I use FEH inside a home made digital picture frame.

I have Ajaxplorer as a web interface to manage the pictures.

It appears that once FEH is started in slideshow mode, it will not reupdate its filelist when the content of the directory is changed.

Is there a way to make it check for changes, eithet automatically or through some sort of signal?

Thanks!

Nico

**Comment by derf** [comment]
Sorry for the (really late) reply. Just in case it's still relevant: feh supports --reload, which will also reload the filelist and thus adapt to changes in the directory.
