### ISSUE TITLE
please consider adding transition effects

### ISSUE THREAD

**Issue by devZer0** [derf/feh#145]
Please consider adding transition effects like soft cross-fade or similar. (like these: http://www.ffiles.com/flash/photo_galleries/simple_slideshow_with_18_transition_effects_3144.html ) 

Perhaps provide an programming example how to add such. 

Maybe it`s even possible to make transition-effect-modules "pluggable" for easier integration into feh ?

**Comment by Anachron** [comment]
Bump. :)

**Comment by derf** [comment]
Not going to happen in the foreseeable future, sorry

**Comment by NicTanghe** [comment]
Bump. :)
