### ISSUE TITLE
copy file path+filename to clipboard.

### ISSUE THREAD

**Issue by jadedgnome** [derf/feh#155]
On the main menu add a copy file path to clipboard option.

**Comment by SRGOM** [comment]
I see that xclip process doesn't exit. Is that expected or am I seeing an abnormal behavior, or is the xclip that is at fault? (feh version 2.9.3)
Steps:

    feh --action1 "echo %F| xclip -sel clip" /tmp/diff.png
    killall -9 xclip; ps aux | grep xclip # should show only the grep process
    #Hit 1 now
    ps xua | grep xclip # Shows the new xclip process
    # Hit Esc on feh 
    ps xua | grep xclip # Still shows the new xclip process
    # Close the shell 
    ps xua | grep xclip # Still shows the new xclip process

**Comment by SRGOM** [comment]
Turns out its an xclip related issue...

**Comment by derf** [comment]
This is a feature, or rather a necessity of X11 design, and not related to feh.

In X11, the clipboard is not buffered / stored by the X server, but rather by whichever application was the most recent to put something into the clipboard. So xclip has to keep running in the background to provide the filename for pasting.

**Comment by addisonklinke** [comment]
@derf After pressing 1, should Ctrl + V be able to paste the filename into any other application? If I remove the `xclip` pipe, I'm getting the echo to terminal fine, but with the pipe it's not overriding my clipboard
