### ISSUE TITLE
Rotation without modifying photos on disk

### ISSUE THREAD

**Issue by fturco** [derf/feh#167]
This is a feature request. I'd like to rotate photos without saving changes to the hard disk. At the moment the "<" and ">" keys immediately save changes, which is inconvenient, as I should not touch the original photos. Perhaps a separate key for saving changes to disk should be implemented if it doesn't exist yet.

**Comment by 0xACE** [comment]
I'd just like to add that this is a feature I'm missing in feh. I'm using feh as a image viewer, I expect it to __never__ edit the original file. If I want to edit a image, I would edit it in a image editor.

If the developers have no interest in implementing this feature, could you point out where the relevant code for this problem resides?

**Comment by derf** [comment]
I will implement this, however the imlib2 rotation code is not as nice as I thought. So it's gonna take a while until it's supported.

**Comment by bugmen0t** [comment]
This would also be useful in the case where the user has read-but-not-write rights on the image.

(Thank you so much for this software btw.)
