### ISSUE TITLE
--start-at not working with absolute image paths (in KDE)

### ISSUE THREAD

**Issue by int-ua** [derf/feh#174]
I've edited feh.desktop command line to be 

```
feh --auto-zoom --scale-down --borderless --start-at %F *
```

trying to replicate eog behavior which is ideal for me, but I want a system with minimum GTK. And now I'm getting this:

```
feh ERROR: --start-at /home/user/directory/filename.jpg: File not found in filelist
```

Since passing absolute path is not an error, it looks like a feh problem.

**Comment by derf** [comment]
Fixed in 55c27c4babcf63989192f930ba7a75dac691e1e5
