### ISSUE TITLE
control feh from terminal

### ISSUE THREAD

**Issue by teleshoes** [derf/feh#182]
it would be LOVELY to handle keyboard events in the terminal the same way that keyboard events are handled in the main window.

i find that i use feh over ssh surprisingly often, from my laptop to my htpc. it would be nice to use slideshow, but instead i have to quit and open the next image.

ive hacked an ncurses key handler onto main.c, but its too hideous to PR. curious to know what you and other folks think of this

**Comment by derf** [comment]
This sounds useful to me too, though it might be a bit tricky to distinguish between reading files / filelists from stdin and reading commands. I'd prefer a patch which doesn't introduce an additional dependency, though.

**Comment by derf** [comment]
feh now has experimental support for reading keyboard events from the terminal. Some keys (e.g. space) aren't handled yet, but I should be able to wrap that up for the next release

**Comment by derf** [comment]
support is pretty stable and somewhat more complete now
