### ISSUE TITLE
Segmentation fault on tiny 1×1 gif

### ISSUE THREAD

**Issue by JulienPalard** [derf/feh#184]
Got a segfault on feh while trying tiny gif files found on stackoverflow:

    echo 'R0lGODlhAQABAAAAACwAAAAAAQABAAA=' | base64 -d > /tmp/empty.gif
    feh /tmp/empty.gif 
    Segmentation fault

They're probably invalid, I understand that, but segfault seems not appropriated.

    # apt-cache policy feh
    feh:
      Installed: 2.12-1
      Candidate: 2.12-1

**Comment by Ferada** [comment]
The GIF is probably invalid, though at least ImageMagick doesn't crash:

    % display /tmp/empty.gif                                                                                                                                                                  Mon Feb 23 10:16
    display: corrupt image `/tmp/empty.gif' @ error/gif.c/ReadGIFImage/1369.

However this is a problem in the Imlib2 GIF loader (tested with
`1.4.6-r2` and fresh feh):

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff2970dec in load () from /usr/lib64/imlib2/loaders/gif.so
    (gdb) bt
    #0  0x00007ffff2970dec in load () from /usr/lib64/imlib2/loaders/gif.so
    #1  0x00007ffff6e9f3b8 in ?? () from /usr/lib64/libImlib2.so.1
    #2  0x00007ffff6e82bdb in imlib_load_image_with_error_return () from /usr/lib64/libImlib2.so.1
    #3  0x000000000040b7f4 in feh_load_image (im=im@entry=0x636d98, file=file@entry=0x62a090) at imlib.c:252
    #4  0x000000000041d019 in winwidget_loadimage (winwid=winwid@entry=0x636d60, file=file@entry=0x62a090) at winwidget.c:764
    #5  0x000000000041e95e in winwidget_create_from_file (list=list@entry=0x62a100, name=name@entry=0x636d30 "feh [1 of 1] - /tmp/empty.gif", type=type@entry=1 '\001') at winwidget.c:126
    #6  0x0000000000417873 in init_slideshow_mode () at slideshow.c:62
    #7  0x0000000000405d89 in main (argc=2, argv=0x7fffffffdfe8) at main.c:78

**Comment by derf** [comment]
closing the report since it is an imlib2 issue.
