### ISSUE TITLE
Filelist doesn't support HTTP URLs

### ISSUE THREAD

**Issue by PooSham** [derf/feh#186]
feh version 2.3

Running `feh -f http://example.com/images.txt` where images.txt holds a list of images, doesn't work. I get the following error message:

> feh: No loadable images specified

**Comment by PooSham** [comment]
I want to use feh as a fullscreen slideshow monitor without needing to ever touch it. This would make my life much easier.

**Comment by derf** [comment]
For now, you should just use `curl -s http://example.com/images.txt | feh -f -`. The feature doesn't seem too useful to me, especially because it wouldn't work with filelist-reload anyways at the moment.
