### ISSUE TITLE
A way to use gvfs trash

### ISSUE THREAD

**Issue by thorwil** [derf/feh#187]
I would like to have a way to put images into Gnome/gvfs trash, ideally bound to the Delete key for consistency with the rest of my environment.

Current configuration options are not sufficient to achieve this. First it is complicated by not allowing commands in ~/.config/feh/keys. Always having to use something like `feh --action 'gvfs-trash %f' .` is a nuisance, especially if you want to use other actions, too.

Then it seems that attempting to rebind Delete is ignored.

**Comment by derf** [comment]
All of this is possible, just not very intuitive (and partially undocumented — I'll fix that).

* unbind the Delete key from its default in ~/.config/feh/keys (either add an empty `remove` line, or bind it to any other button you want)
* map the Delete key to some action (either `action` for the default, or for instance `action_9` if you want to leave --action free in case you need it elsewhere)
* Add `--action` or `--action9` as a default in ~/.config/feh/themes: add or extend the line starting with feh, e.g. `feh    --action9 "gvfs-trash %F"` — The "feh" theme is used for default options when no other theme is specified on the commandline. Note that you do need double quotes, single quotes don't work at the moment.

**Comment by thorwil** [comment]
Except for feh warning about non-existing files for each one moved to the trash when stepping backwards, which is of course logical, this works fine. Thank you very much for your work!
