### ISSUE TITLE
support for multiupule desktops with wallpapers

### ISSUE THREAD

**Issue by hidroto** [derf/feh#189]
i use two displays and would like to say
    feh --bg-max IMAGE_ONE --bg-center IMAGE_TWO
and have the IMAGE_ONE be in max mode on desktop one and IMAGE_TWO centered on the second display.

as it stands the last of the --bg-* options is used for both images such that they are centerd.

**Comment by derf** [comment]
This would complicate things a lot (though mostly inside of feh, not so much from a user persective). While feh seems to be a pretty decent wallpaper setter, its main purpose is displaying images, so I don't want to refactor most of the wallpaper setting code just to support that use case too. Sorry.
