### ISSUE TITLE
Stop on last image

### ISSUE THREAD

**Issue by rr-** [derf/feh#191]
Right now after we hit the last image in the file list, we have two options:
- have feh cycle the file list back to the beginning
- have feh exit.

It would be nice if there was a third option, that allows feh to stay on the last image and do nothing. This would be useful for following reasons:
1. When feh cycles: in large file lists user might not immediately recognize the images he's already seen.
2. When feh exists: user might cycle too fast and might want to go back to the previous image... nope. Program has already exited.

**Comment by ikk00** [comment]
+1. i also would like to see this feature.
