### ISSUE TITLE
Remove current file from filelist when image is shown

### ISSUE THREAD

**Issue by limelime** [derf/feh#198]
Is there a way for feh to remove current file from filelist when image is shown through slideshow mode, without human interaction? I simply want to continue the slideshow where I left off.

I know that pressing DELETE will do that but I don't want to press that button(There are thousands of images).
I was exploring the --action option but there, it requires user to press ENTER.

**Comment by derf** [comment]
No, there's no straightforward way to do that. You can probably come up with some kind of hack (perhaps abusing --info to execute a command when an image is shown), but feh does not support such a thing out of the box.
