### ISSUE TITLE
Raspberry Pi - Tinycore linux; no binary

### ISSUE THREAD

**Issue by viconofrei** [derf/feh#214]
Hello,
Is there a way to include feh in this distro?
It would be nice since no image viewers work in currently version 6.0. Tried to install several and absolutely no result.
Some of them block(freeze) others don't recognize image files.

Thanks in advance!!!

**Comment by derf** [comment]
I wouldn't know. I only work on feh itself, please talk to a distro maintainer if you want it to be included there.
