### ISSUE TITLE
Feature Request: add key to toggle auto-zoom

### ISSUE THREAD

**Issue by cpoakes** [derf/feh#218]
In addition to the checkbox for "auto-zoom", it would be convenient to have a key to toggle auto-zoom.

Attached patch (tested against feh 2.12, debian jessie), configures (capital) "Z" as toggle key.
[toggle_auto_zoom.txt](https://github.com/derf/feh/files/90584/toggle_auto_zoom.txt)
.

**Comment by ulteq** [comment]
Great idea, if you ask me.

**Comment by derf** [comment]
yup, this makes feh more consistent and consistency is good. Thanks!
