### ISSUE TITLE
feh will display an incompletely loaded image (mid file copy)

### ISSUE THREAD

**Issue by yournameistaken** [derf/feh#223]
I am using feh as a slideshow and am using the reload option to see if a file has changed every X seconds.  I have a background script that is overwriting the file, and if feh tries to reload the image while a new image is being copied, it will display a partial image.  Maybe add a file integrity check before loading/displaying the image to make sure it is a complete image?  (Greatly appreciate the program by the way, thank you).

**Comment by derf** [comment]
That is an option, but would break other use cases, such as viewing broken
downloads or files which were only partially restored from a corrupted file
system.

There's an easy (and even pretty standard) solution though: assuming you're
displaying foo.jpg, run 'cp whatever foo.jpg.new; mv foo.jpg.new foo.jpg'.
The mv is an atomic operation, so no matter when feh choses to read the file,
it will either get the intact old or the intact new version.

**Comment by yournameistaken** [comment]
Wow, thanks for the quick and detailed response.  Linux is obviously not my forte, and I didn't realize that mv was atomic.  This looks good so far!
