### ISSUE TITLE
Can't set wallpaper under GNOME

### ISSUE THREAD

**Issue by zagortenay333** [derf/feh#225]
Am running fedora 23 with gnome-shell `3.18`.

**Comment by derf** [comment]
Indeed. gnome does not use the X background, but instead does things its own way.

However, it's easy to change the background in gnome directoly, using e.g. `gsettings set org.gnome.desktop.background picture-uri file://something`. So I'd rather not change feh to also support gnome, but instead update the manpage to point to this method.

Thanks for pointing it out!
