### ISSUE TITLE
.desktop file should have line 'NoDisplay=true'

### ISSUE THREAD

**Issue by Boruch-Baum** [derf/feh#228]
The .desktop file packaged along with feh, and used for xfreedesktop GUI integration, should include the line 'NoDisplay=true'. This will suppress feh from being included in GUI application menus, but will still allow it to be integrated with GUI file managers. The current situation creates an menu entry for feh that opens the first image feh finds in whatever is the systems default folder ( usually ${HOME} ), and if the user has no images in that folder, feh will silently fail, and the user will think its a broken program. In any case, without a file selector the presence of an entry for feh on a GUI menu is of little utility.

**Comment by derf** [comment]
Fixed in feh 2.15
