### ISSUE TITLE
new release 2.5 broke w command and --scale-down in bspwm

### ISSUE THREAD

**Issue by EmmanuelPerezP** [derf/feh#229]
ok so i have Arch linux with bspwm tiling window manager, before the update in 2.4 i used to use the  `feh --scale-down --keep-zoom-vp filename ~/directory`
command alot, when i made the image a floating window i could resize the window and the image would resize with it, now it doesnt do that, now it only resizes when i pass to the next image.... and the `w`command to resize the window doesnt work either...

my `feh -v` output is 
`feh version 2.15` 
`Compile-time switches: curl exif help stat64 xinerama`

**Comment by dsohler** [comment]
Always scales all images down to the size the window had when opening the first image when having the following set as default theme in `.config/feh/themes

    feh --scale-down \
        --image-bg black \
        --sort name \
        --no-menus \
        --magick-timeout -1 \
        --force-aliasing \
        --title "[%u/%l] %n (%wx%h)" \

I’m using openbox in Arch Linux

    $ openbox --version
    Openbox 3.6.1
    
    $ uname -rms
    Linux 4.5.0-1-ARCH x86_64

When downgrading to version 2.14.2 of feh it all works as expected again.
