### ISSUE TITLE
Feature Request: add option to sort name/filename case insensitive

### ISSUE THREAD

**Issue by jmcamp** [derf/feh#250]
would be nice to have an option like "--sort iname" and "--sort ifilename" for case insensitive sorts.

**Comment by xelxebar** [comment]
Just a thought, but by default feh displays images in the order that the file path arguments are given. You could create a simple script that sorts arguments then feeds them to feh:

    #!/usr/bin/env sh
    \printf "%s\n" "${@}"       \
        | \sort --ignore-case   \
        | \xargs \printf '%s\0' \
        | \xargs -0 \feh

**Comment by derf** [comment]
Yup. There's always going to be special sort modes which feh does'nt support out of the box, and this is one of those. Please use a script like the one provided by @xelxebar above.
