### ISSUE TITLE
how to jump to say image 450 in a 700 image directory 

### ISSUE THREAD

**Issue by shirishag75** [derf/feh#262]
I am using feh 2.17.1 . I do see that feh obviously uses some logic to show images. In mine, it shows images in ascending corner, i.e. from oldest image first .  Is there a way to tell to feh to start from say 450th image in a 700+ images in a directory. Is there a way do it ?

**Comment by derf** [comment]
Yeah, using `--start-at`. You can write a shell script to figure out the name of the 450th (or whatever-th) image you want to start with and run `feh --start-at $foo`.

**Comment by shirishag75** [comment]
that is going to be the problem.

**Comment by xelxebar** [comment]
Here's a thing:

    #/usr/bin/env sh
    feh --start-at "${450}" "${@}"

**Comment by derf** [comment]
Yeah, something like that. I don't have the time to come up with a "proper" solution, but there should be plenty of places where you can find help with writing / improving a shell script for this task.
