### ISSUE TITLE
Desktop file doesn't support non-local targets

### ISSUE THREAD

**Issue by xelxebar** [derf/feh#264]
## Summary

Despite feh having support for viewing remote URIs (e.g. `feh https://feh.finalrwind.org/logo.png`), the `feh.desktop` `Exec` only passes through local file arguments. This causes unexpected breakage when an XDG-aware program tries to pass along a remote URI.

## Demonstration

    $ gtk-launch feh.desktop 'https://feh.finalrewind.org/logo.png'
    feh WARNING: ./.foo - no Imlib2 loader for that file format
    ...

## Proposed fix

We should probably set the `Exec` line with a `%U` aragument instead of `%F`. Here is a patch which does just that:

    --- a/usr/share/applications/feh.desktop	2016-12-06 07:53:58.183778740 +0900
    +++ b/usr/share/applications/feh.desktop	2016-12-06 07:54:32.551024785 +0900
    @@ -4,7 +4,7 @@
     GenericName=Image viewer
     GenericName[en_US]=Image viewer
     Comment=Fast Imlib2-based Image Viewer
    -Exec=feh %F
    +Exec=feh %U
     Terminal=false
     Type=Application
     Icon=feh

With the above patch, the gtk-launch example above launches feh as expected.

**Comment by derf** [comment]
Indeed. This also means that feh might be opened with file:// URIs and thus incur some overhead because it uses libcurl to open those, but I guess that is acceptable. And at least gtk-launch does a pretty good job of scrubbing those. Thanks!
