### ISSUE TITLE
Window title not refreshed with the "--title %z" option

### ISSUE THREAD

**Issue by Dupond** [derf/feh#266]
Hello,

I'm having an alias to display some infos about the image in the window title :
```alias feh='feh --title "%n (%wx%h, %S) - %z%% - feh [%u/%l]"'```

But it doesn't work well :
1. The zoom is not displayed at all when feh is launched (displaying "... - % - feh..." whereas I would expect "... - 1.00% - feh...") ;
2. When the zoom key is triggered (I have the "+" and "-" custom keys defined for this in .config/feh/keys), the zoom level is not updated (so, it's still not displayed at all).

In fact, the only moment when the zoom level is displayed is when I go to the previous or next image. Then "1.00%" is displayed (but still not updated when zooming, so it's pretty useless).

Is there a way to have the window title updated each time the zoom keys are pressed ?

Thanx for your help,
Best regards,
Dupond

**Comment by Dupond** [comment]
Is this reproduceable ? I'm wondering if this is really a bug, or if it's my config that is bad.
Can someone observe the same behaviour ?

Thanx,
Dupond

**Comment by derf** [comment]
This really is a bug, thanks for reporting it :)

The window title was initialized before loading the image (hence the missing zoom data) and then only updated when changing between images, not when zooming the currently active one.

**Comment by Dupond** [comment]
I think this bug should be reopened : if an image is displayed from the thumbnail mode, the zoom value (if added in --thumb-title) isn't updated yet.
Thanx !
Best regards,
Dupond
