### ISSUE TITLE
No way to turn off filenames in thumbnail mode

### ISSUE THREAD

**Issue by jidanni** [derf/feh#267]
User wishes to see a grid of thumbnails, but ends up with

![oow](https://cloud.githubusercontent.com/assets/1230959/21584449/5957072e-d0e3-11e6-8ff1-d7ee781daf7d.jpg)

due to his long file names, which there is no way to turn off.

User sees

```
 -@, --title-font font
             Set font to print a title on the index, if no font is specified,
             no title will be printed.
```
But apparently that is something different.

Feh 2.18 Debian.

**Comment by jidanni** [comment]
OR why not list this hack on the man page
http://unix.stackexchange.com/questions/116421/is-there-an-approach-to-have-feh-thumbnails-do-not-display-filename

**Comment by derf** [comment]
Or just use `--index-info ""` to disable the display of filenames.
