### ISSUE TITLE
Feh can not display bmp format

### ISSUE THREAD

**Issue by jadiah** [derf/feh#276]
I like feh, but i have lot of images in BMP format which Feh cant display (not BMP2 or BMP3, the simple BMP format), so i forced to install second image viewer for it, is there a way to make Feh work with BMP and can you do it?

> $ identify image.bmp
> image.bmp BMP 2376x1680 2376x1680+0+0 8-bit sRGB 11.98MB 0.020u 0:00.019
> $ feh image.bmp
> feh WARNING: image.bmp - No Imlib2 loader for that file format
> feh: No loadable images specified.

**Comment by derf** [comment]
Did you try `--magick-timeout 5`? As long as you have convert (imagemagick) installed it should work fine.
