### ISSUE TITLE
--reload makes the image repeat both horizontally and vertically

### ISSUE THREAD

**Issue by Pablo1107** [derf/feh#277]
When I executed a command like " feh /tmp/mpdcover.png -Z -B white -R 5 " the image instead of reloading in the same place as it was loaded, it repeated both axis. Some idea if this is a bug?

**Comment by ulteq** [comment]
I can't reproduce that with feh 2.23.

**Comment by derf** [comment]
I can't reproduce that with 2.26.1 either.
