### ISSUE TITLE
Window title still not updated when zooming from thumbnail mode

### ISSUE THREAD

**Issue by Dupond** [derf/feh#280]
Hello !

Since I can't reopen my closed issue [here](https://github.com/derf/feh/issues/266), I'm afraid no one will ever see [my last post](https://github.com/derf/feh/issues/266#issuecomment-281974546) ;) So I've decided to submit this new issue. I hope it's OK for you...

The issue is almost fixed, but not when zooming in an image opened from the thumbnail mode. Here is a copy/paste of my last post :

>  I think this bug should be reopened : if an image is displayed from the thumbnail mode, the zoom value (if added in --thumb-title) isn't updated yet.
>
> Also, if the --title is customized (e.g. with the zoom and height/width values), it doesn't make sense for the thumbnails window. So I think we should have a way to set the title for the thumbnails window (I don't mean --thumb-title for an image opened from the thumbnail window, I hope I'm clear... sorry for my poor english).

Steps to reproduce :

1. `feh -t --title="%z%%" *.*`
2. Click on an image to open it
3. Zoom in (keypad +)
4. The window title still shows "1.00%"

Thanx for your help !
Best regards,
Dupond

**Comment by derf** [comment]
I actually noticed the new reply, I just didn't get around to working on it yet. It's fixed now :)

**Comment by Dupond** [comment]
Cool ! What do you think about my suggestion of a window title option for the thumbnail mode ? Do you want me to open a separate ticket ?

**Comment by derf** [comment]
I don't think that would make sense. The user should know wether they open feh normally or as thumbnail window, so they can just set --title to something appropriate themselvels or configure their feh themes / shell aliases to do so. No need for a new option exclusively for the thumbnail list.

**Comment by Dupond** [comment]
Mmm... Not sure I've been understandable.

I have an alias for feh to customize it. Here it is :
`alias feh='feh -auto-rotate --scale-down --title "%n (%wx%h, %S - zoom %z) - feh [%u/%l]" --thumb-title "%n (%wx%h, %S - zoom %z) - feh"'`
So, for example, when I open an image (even from a script or from dmenu, thanx to the alias) the title shows :
`2017-03-02--scrot.png (1368*768, 60k - zoom 0.92) - feh [1/1]`
But if I open it with the `-t` option, the thumbnail list window has a title such as :
`(x, - zoom 1.00) - feh [0/1]`
So it doesn't mean anything, and it's not relevant at all : "zoom 1.00" is obviously wrong, since it just means that the image is displayed as a thumbnail, and "[0/1]" just makes no sense at all...

If we don't have a specific option, how would it be possible to customize the window title AND to have a thumbnail list window titlte that would make sense ?

I hope it's more clear now ;)

Best regards,
Dupond

**Comment by Dupond** [comment]
Just wanted to know if my previous message had been read, by any chance...
derf, since you seem to always close the issues by yourself, it's impossible for OP to re-open them, so it's hard to have a discussion.
Thanx for your great software,
Best regards,
Dupond

**Comment by derf** [comment]
Read yes, acted upon now. May take a while, sorry.

**Comment by Dupond** [comment]
Why sorry ? I just wanted to have the opportunity to discuss about it.

**Comment by Dupond** [comment]
Since the thumbnail list window title is now "feh [thumbnail mode]", it seems to me that this bug is fixed (or, more precisely, it doesn't exist anymore...)
ulteq, I'm not sure why you haven't closed it... have you thought there's still an issue that I'm not conscious of ?
Anyway, thanx for all the work done on this amazing piece of software !

**Comment by ohnonot** [comment]
Does this mean that in thumbnail mode I can have only "feh [thumbnail mode]" as window title?

Because I've just been struggling with a way to change that...
