### ISSUE TITLE
Window icon via cmd-line or similar

### ISSUE THREAD

**Issue by ikk00** [derf/feh#282]
Hi. 
Thanks for your work on my favorite image viewing program.

Since I'm using 'feh' by not installing it in the system. Is it possible to have main window icon set from the command line or in a similar way, independent of desktop managers?

If not, I would like to feature request it. Could be just done as a feature for a 24-bit color desktop mode only, and fail on all other color modes. Since users there probably do not rely on  features like visual customizations. Should be simpler to code this way. I can provide code snippet in C that just does that if it would help.

**Comment by derf** [comment]
Not gonna happen, sorry
