### ISSUE TITLE
~/.thumbnails should be set to $XDG_CACHE_HOME/thumbnails/

### ISSUE THREAD

**Issue by legrostdg** [derf/feh#283]
`$XDG_CACHE_HOME/thumbnails/` is already used by several other applications, it would be nice if feh used this, too.

**Comment by legrostdg** [comment]
(instead of using `~/.thumbnails`)

**Comment by Ferada** [comment]
AKA follow the [freedesktop](https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html) spec. Agreed, it would be great to have one directory less I think.

**Comment by derf** [comment]
I just merged #291, so the next release will use XDG_CACHE_HOME. Thanks for the patch :)
