### ISSUE TITLE
text not displaying in jpeg

### ISSUE THREAD

**Issue by stooj** [derf/feh#285]
The attached jpeg has some text that is invisible when opened with feh or sxiv. It seems to render fine on github in Firefox.

Original file:
![exploring_the_paint_editor](https://cloud.githubusercontent.com/assets/430541/24223996/f96ce73a-0fac-11e7-9c57-0fdf4c6999c6.jpg)

Screenshot of the image open in feh:
![exploring_the_paint_editor_view_in_feh](https://cloud.githubusercontent.com/assets/430541/24224339/c7fbcd72-0fae-11e7-9342-562959e13380.jpg)

Somehow all the black text is being stripped out. It is presumably some weird corner case with the image itself, but it renders correctly with eog/pinta/gimp

I've also reported this to [sxiv](https://github.com/muennich/sxiv/issues/272) in case there can be some cross-platform comparison.

**Comment by Ferada** [comment]
`display` / ImageMagick is even better, showing a black background. So the file is in CMYK colorspace:

    > identify f96ce73a-0fac-11e7-9c57-0fdf4c6999c6.jpg
    f96ce73a-0fac-11e7-9c57-0fdf4c6999c6.jpg JPEG 844x739 844x739+0+0 8-bit CMYK 893KB 0.000u 0:00.050

Both GIMP and Krita can open it correctly, GIMP autoconverts it to RGB, while in Krita you've got to explicitly convert it.

Also, again, Imlib2, not feh, issue.

**Comment by stooj** [comment]
I've reported this upstream: https://phab.enlightenment.org/T5416

**Comment by Ferada** [comment]
@stooj this looks fixed, at least with latest Imlib2 installed, confirm?

**Comment by stooj** [comment]
I've not been able to test the git version of imlib2 yet, but the issue is still present with imlib 1.5.1 and feh 3.2.1

**Comment by Ferada** [comment]
There hasn't been a release for Imlib2 yet, the fix was after 1.5.1. I guess this can stay open as a reminder, but it's definitely fixed.

**Comment by stooj** [comment]
\o/ New imlib2 release has landed and this is fixed. Thanks so much
