### ISSUE TITLE
Feature request: select where image starts when it is larger than the window

### ISSUE THREAD

**Issue by Xitian9** [derf/feh#295]
Commit dfe3c40f80f77a800479c31a51b1f3b1f648b0ea created a change in behaviour. Previously when an image which was too large for the screen was displayed, the top-left corner of the image would be placed in the top-left corner of the window; afterwards the image would be centred in the window. This works badly when viewing sequential material, when you would want to start in the top-left (or maybe top-right for some languages).

Could there be an option/command-line flag added to select where the image starts in these cases.

**Comment by derf** [comment]
Sounds like a useful addition to #278

**Comment by derf** [comment]
Use `--offset +x+y` for that. The option is experimental and therefore not yet documented.

Please let me know how it works for you.

**Comment by Xitian9** [comment]
This does what I want it to. Unless you wanted to leave this open until documentation is added, this issue can be closed.
