### ISSUE TITLE
PNG fourCC chunk not correctly validated

### ISSUE THREAD

**Issue by timetoplatypus** [derf/feh#296]
This is a *very* minor problem, but should be addressed so that feh complies with the PNG specification. The second component of a PNG chunk is a four-character code. The third byte of this fourCC must be an uppercase ASCII character in order to comply with specification. Feh does not currently check this third byte, so it doesn't matter what is at that location as long as the CRC32 checks out. To address this, feh should do the same thing it does when the CRC32 is incorrect: print a warning to console (no need to stop execution or anything).

**Comment by derf** [comment]
Hi,

Thanks for reporting this – however, feh relies on Imlib2 to parse and load image formats, so this cannot be fixed in feh itself. Please report it to the Imlib2 maintainers.

**Comment by timetoplatypus** [comment]
Sounds good, will do.
