### ISSUE TITLE
Opening images from thumbnail mode with keyboard

### ISSUE THREAD

**Issue by mrichar1** [derf/feh#297]
Apologies if I'm missing something obvious, but there doesn't seem to be a way to launch images from thumbnail mode using the keyboard(though it seems possible to select them).

For example, running `feh -t` shows all the thumbnails. Left/right/space seem to show the selection changing, but I can't find any key to open it (though mouse-clicking works fine).

**Comment by derf** [comment]
Hi,

it's not prominently featured in the manual, but the `render` key (by default `R` or `keypad begin`) does just that :)
