### ISSUE TITLE
BackSpace camel case not documented for key binding

### ISSUE THREAD

**Issue by bruva** [derf/feh#302]
The problem occurs with feh 2.19.

The following is the minimal example for `~/.config/feh/keys`:

```
close
prev_img
close Backspace
```

Pressing <kbd>⌫</kbd> (backspace key) has no effect (does not close the current window). Instead when starting feh the following error is given:

```
feh WARNING: keys: Invalid keysym: Backspace
```

 Only using:

```
close
prev_img
close BackSpace
```

makes the backspace key work (for this example closing the current window).

But in feh(1) the string `BackSpace` (camel case) is never mentioned. The manual page instead gives the impression one should use the string `Backspace` (no capital `S`):

```
     p, ⟨Backspace⟩, ⟨Left⟩ [prev_img]
             Show previous image. Selects the previous image in thumbnail
             mode.
```

**Comment by derf** [comment]
Indeed, that's misleading. Thanks for pointing it out.
