### ISSUE TITLE
Off-by-one bug in pixel rendering

### ISSUE THREAD

**Issue by re-curse** [derf/feh#305]
There is an off-by-one bug in the rendering, most notably in higher zoom levels without antialiasing blurring the mistake. There seems to be a row/column added/deleted every skipped line. This bug is not file format specific.

At first I thought it was an optical illusion until I tested with a checkboard pattern and measured pixels.

As for severity, it makes feh unsuitable for displaying QR codes. Found out the hard way. :(

**Comment by Ferada** [comment]
Could you post an example?

**Comment by re-curse** [comment]
Sure, here's a checkboard pattern, 1px x 1px.
![check](https://user-images.githubusercontent.com/1657395/27549482-b32cedce-5a61-11e7-8ddd-f19300d0c3f8.png)

When rendered it produces something like this image:
![save](https://user-images.githubusercontent.com/1657395/27549527-d96fc3d0-5a61-11e7-89a9-45b03327b15f.png)

Even though the scaling is 1:1, the 1-unit square pixels alternate between 57x57 and 57x**58**.

It's very subtle.
