### ISSUE TITLE
SVG not opening

### ISSUE THREAD

**Issue by TrainerRed151** [derf/feh#309]
> feh --magick-timeout 1 Pictures/Flags/EthanFlag.svg
feh WARNING: /tmp/feh_005872_000001_EthanFlag.svg_cC1kq6 - No Imlib2 loader for that file format
feh WARNING: Pictures/Flags/EthanFlag.svg - No Imlib2 loader for that file format
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information

**Comment by derf** [comment]
This is probably because your ImageMagick is missing `rsvg` and hence cannot convert the SVG file. Please try again with feh 0c5ed69 – as of this commit, ImageMagick errors are forwarded to the user by default.

**Comment by derf** [comment]
feh v2.19.2 shows ImageMagick error messages and hence should not lead to confusion regarding unloadable files. Closing this issue.
