### ISSUE TITLE
Segfault (core dumped) caused by pressing XF86Back and XF86Forward keys

### ISSUE THREAD

**Issue by sector-f** [derf/feh#312]
Pretty much exactly what the issue title says: While viewing images with feh, pressing either the `XF86Back` or `XF86Foward` keys causes an immediate segfault. These are apparently media keys used to go back/forward in your web browser history.

My version of feh was installed from Arch Linux's official repo; `feh --version` prints:
````
feh version 2.19.1
Compile-time switches: curl exif help stat64 xinerama
````

**Comment by derf** [comment]
Indeed, I was using isprint and isspace in the key handling code without checking whether the argument fit into an 8bit signed char first – and without knowing that passing a value which does not fit inside a char is undefined behaviour, which glibc implements as a segmentation fault. Oh well :)

It's fixed now, a bugfix release will follor shortly.
