### ISSUE TITLE
Feh not respecting --no-fehbg option

### ISSUE THREAD

**Issue by hiteshpaul** [derf/feh#314]
I am currently using i3 as my window manager and run feh using this command:
`exec_always feh --no-fehbg --bg-scale ~/path/to/some/wallpaper.jpg`

Eventhough I pass the --no-fehbg option, I find a .fehbg executable file lurking inside my home folder. 

Details of my system:
OS: Arch Linux x86_64
feh version 2.19.2
Compile-time switches: curl exif help stat64 xinerama

**Comment by derf** [comment]
I cannot reproduce that here. Is it really a _newly_ _created_ executable? Does feh recreate it when you manually remove it and then run the above command again?

**Comment by hiteshpaul** [comment]
Sorry, it was my bad! Seems I had a line in my config which calls the `feh` command again without the `--no-fehbg` option. Closing this issue.
