### ISSUE TITLE
Feature request: Support for umlauts and special characters in keybindings

### ISSUE THREAD

**Issue by thurse93** [derf/feh#318]
I'm using a german keyboard layout and the umlauts are keys which I frequently map in other applications. *ö*, *ä* and *ü* replace the *;* , *'* and *[* keys on the standard us layout so the position is too convenient to leave them unmapped (especially if you're using i3-wm's *jkl;* / *jklö* movement). So is there a chance this could be implemented in the future?

**Comment by derf** [comment]
It already is, but the manual may not be clear enough on how to use them.

feh expects X11 keysym names in its configuration. For "normal" keys, they correspond to the letters printed on the keyboard, for others, they are strings like `Delete` or `braceleft`. Umlauts are known to X11 as special strings, e.g. `odiaeresis` for `ö`. By using these, you can bind actions to Umlaut keys. Use `xev` to find out the names of other keys.

I'll see how I can improve the manual in this regard.
