### ISSUE TITLE
';' flag for actions do not reload captions

### ISSUE THREAD

**Issue by caradag** [derf/feh#321]
If an action changes or add a caption for an image, it is not displayed despite of using the ; flag.
To see the new caption is necessary to press the r key to force reload.

**Comment by derf** [comment]
I cannot reproduce that here. Could you please give me the commandline you are using?

**Comment by caradag** [comment]
Thanks for following this up!
This is the command. This is within a script where $_fname is the name of an image in the current directory that I'm opening.

feh --action '[Mover a DELETED]mv %F /home/camilo/Desktop/selecciones/Deleted/' \
     --action1 '[Copiar a Seleccion 1]cp %F /home/camilo/Desktop/selecciones/S1/%N' \
     --action2 '[Copiar a Seleccion 2]cp %F /home/camilo/Desktop/selecciones/S2/%N' \
     --action3 '[Copiar a Seleccion 3]cp %F /home/camilo/Desktop/selecciones/S3/%N' \
     --action4 '[Agregar a Lista 1]echo ./%n >> lista_seleccion1.feh' \
     --action5 '[Agregar a Lista 2]echo ./%n >> lista_seleccion2.feh' \
     --action6 '[Agregar a Lista 3]echo ./%n >> lista_seleccion3.feh' \
     --action9 '[Editar caption]mkdir captions; touch captions/%N.txt; libreoffice --nologo --writer captions/%N.txt' \
     -F \
     --caption-path "captions/" \
     --auto-rotate \
     --start-at ./"$_fname"

Cheers

**Comment by derf** [comment]
Hmm... Could you enter `libreoffice --nologo --writer some_file.txt; echo "Libreoffice returned"` in a shell and tell me when it prints "Libreoffice returned"?

If it happens while the LibreOffice window is still open, feh is not at fault here – instead, the libreoffice process returns control to the shell so early that the changes feh should pick up are not present yet. If it only happens after you close the LibreOffice window, it's probably a bug in feh.

**Comment by caradag** [comment]
That command works perfect to me. I can enter libreoffice (that I choose to have spell cheking) type the caption and exit.
I think it is not libreoffice at fault, because if there were originally no caption, I can call action 9, add a caption and then call action 9 again, and still no caption is displayed. So it doesn't seem to have something to do with the fact that the FEH might be reloading before libreoffice saves the changes to the caption file.
Does that makes sense?

**Comment by caradag** [comment]
My fault. I'm very sorry. When I was trying that and other things I also did upgrade FEH to the last version, and the issue existed on my previous version (the one provided by the Ubuntu software center) but IT IS SOLVED IN THE CURRENT VERSION
I'm sorry and thanks for keeping such extraordinary piece of software.
