### ISSUE TITLE
--magick-timeout broken (wrong path?)

### ISSUE THREAD

**Issue by fedov** [derf/feh#323]
Trying to view an svg image with "feh --magick-timeout 2 test.svg" results in the following error:

> convert: no decode delegate for this image format `SVG_UZZ2GD' @ error/constitute.c/ReadImage/504.
> convert: no images defined `png:fd:5' @ error/convert.c/ConvertImageCommand/3258.
> feh WARNING: /tmp/feh_029046_000001_test.svg_UZz2gD - No Imlib2 loader for that file format
> feh WARNING: test.svg - No Imlib2 loader for that file format
> feh: No loadable images specified.
> See 'feh --help' or 'man feh' for detailed usage information

Convert seems to do conversion, because there is a file called "fd:4" in the cwd. Its viewable, seems to be a png version of the original. There seems to be some confusion about the path for the tmp file.
This happens with feh 2.19.3 and ImageMagick 6.9.9-11

**Comment by derf** [comment]
This seems to be an ImageMagick bug: the `png:fd:X` syntax (to output a PNG image to a file descriptor) is working fine in v6.8.9-9, but not in 6.9.7-4. The next feh release will include a workaround for this.
