### ISSUE TITLE
feh ERROR: No files found to reload.

### ISSUE THREAD

**Issue by fedov** [derf/feh#325]
I mentioned this recently on irc but since it's not fixed in the new version (2.20) I thougt I'd open an issue, just in case.
When started with a filelist (no filenames as args) and the -R option feh dies as soon as it tries to reload.
Snippet to reproduce:
```
convert -size 50x50  xc:red test.jpg # or just use an existing imagefile
echo test.jpg > LIST
feh -R1 -f LIST
```

**Comment by derf** [comment]
Yup, this was a bug, fixed by #368. Thanks to you for reporting and to @Ferada for fixing it :)
