### ISSUE TITLE
-R Option doesn't work if path specifies Files

### ISSUE THREAD

**Issue by tjaeger** [derf/feh#329]
This won't work `#feh -V -F --auto-rotate -R10 -D4 --randomize ./pictures/*.JPG`
While this works: `#feh -V -F --auto-rotate -R10 -D4 --randomize ./pictures/`

Specifying Files (*.JPG) doesn't reload the Filellist; so it keeps showing the existing (from startup time) list.

feh version 2.20-5-g7eb9d73
Compile-time switches: curl exif xinerama

**Comment by derf** [comment]
Hi!

That's because your shell expands `./pictures/*.JPG` on its own, so all feh sees is ./pictures/foo.JPG, ./pictures/bar.JPG etcetera. It has no way of knowing your original intention.

So, it's not a bug, just shell behaviour ;)
