### ISSUE TITLE
Shell autocompletion flags are not updated

### ISSUE THREAD

**Issue by CapacitorSet** [derf/feh#330]
When I try to autocomplete the flags from zsh, some outdated flags appear (eg. --bg-seamless, which seems to be no longer supported), and some newer flags do not appear (eg. --bg-max).

I installed feh from [the community repo](https://www.archlinux.org/packages/extra/i686/feh/). `feh --version` reports 2.20.

**Comment by derf** [comment]
autocompletion is handled and maintained by zsh, not feh. I'll submit an updated version of the completion script when I have time.
