### ISSUE TITLE
Issue with snap and path

### ISSUE THREAD

**Issue by danensis** [derf/feh#334]
I use this command to examine photographs and copy the better ones to a new directory. 
feh /media/username/SAMSUNG/pictures --recursive --randomize --draw-filename --auto-zoom --fullscreen --action "cp %f /media/username/SAMSUNG/better/%n" * 

In my home directory I have a snap directory containing xnviewmp
~/home/snap/xnviewmp

Despite not having snap in the path for feh it still keeps trying to load the icon images from xnviewmp

Otherwise it works fine - thank you.

**Comment by derf** [comment]
Well yeah, you are specifying `*` on the command line, so feh will recursively scan all folders in your home directory and show their contents, including the xnviewmp icons. You don't need to specify `*` if you're already providing the path `/media/username/SAMSUNG/pictures`
