### ISSUE TITLE
View heic 

### ISSUE THREAD

**Issue by genacide** [derf/feh#336]
Please add the ability to view heic files

**Comment by derf** [comment]
feh itself does not contain code for specific images, but relies on Imlib2 and ImageMagick.

While Imlib2 development has mostly stalled, ImageMagick support for heic seems to be underway. As soon as it is there, you can open heic images in feh by using the `--magick-timeout` option with a non-zero value.

**Comment by vi** [comment]
Implemented the loader: https://github.com/vi/imlib2-heic
