### ISSUE TITLE
.fehbg not updated when setting wallpaper via menu

### ISSUE THREAD

**Issue by sla0101** [derf/feh#339]
Hi,

My Specs;

Slackware 14.2 x64
Kernel 4.13.9
Openbox 3.6.1
feh 2.21
xorg-server-1.18.3
Nvidia gtx 1060 - nvidia-driver-375.6

Slackware had an update to xorg-server-1.18.3, and I compiled 4.13.9, and then reinstalled my nvidia drivers, when I came to the log in prompt and typed 'startx' I was greated with the Feh window open and running on my desktop, with this command from .fehbg;

'feh' '--zoom' 'fill' '-g' '800x600' '--title' 'Feh' '/home/foo/Wallpaper/' 

Before these updates feh was working just fine and the contents of .fehbg would always display the /path of the wallpaper I had set like this before;

feh  --bg-fill '/home/foo/Wallpaper/Numix Blue Slack.jpg' 

With Feh open I would always right click > File > Background > Set Filled

I don't understand or see any relation to an xorg-sever and kernel update to effect this, but I promise you these are all the changes I made to my box.

Now I'm lost as to when I always run feh to set a wallpaper the .fehbg always shows this contents;

'feh' '--zoom' 'fill' '-g' '800x600' '--title' 'Feh' '/home/foo/Wallpaper/' 

What I find odd is that this is the command I use in the Openbox menu.xml to start feh from the Openbox menu, that I have an entry for, I've been doing it this way for several years without problems;

command feh --zoom fill -g 800x600 --title Feh "/home/foo/Wallpaper/"command

**Comment by sla0101** [comment]
I just compiled feh-2.19.3 and it works, .fehbg is changing and working properly as it should.

Then I compiled feh-2.21 and .fehbg did not change, so I don't know I was using 2.21 from when it was released till today, and now it stopped working...

Hmm

**Comment by derf** [comment]
That's a bug I introduced in 2.21, yeah. I completely missed the fact that the wallpaper can also be set via the menu. Thanks for pointing it out!

**Comment by sla0101** [comment]
Hi derf,

Glad to be of service and it looks like 2.22 got the problem! :)

Keep up the great work, I LOVE Feh!

THANKS

**Comment by sla0101** [comment]
Ahhh 2.22 just broke compton from starting, new bug report coming...
