### ISSUE TITLE
2.22 Breaks Compton From Starting

### ISSUE THREAD

**Issue by sla0101** [derf/feh#342]
My sytem specs;

Slackware 14.2 x64
compton - latest git commit - 316eac0_2017.04.30
feh 2.22
Nvidia GTX 1060 - nvidia-driver-375.66
Openbox 3.6.1
xorg-server-1.18.3

I use Feh to set a wallpaper when I log into Openbox. In ~/.config/openbox/autostart.sh this is where feh gets started from, once logged into Opebox;

```. $HOME/.fehbg```

Here's the contents of .fehbg;

```#!/bin/sh```
feh  --bg-fill '/home/foo/Wallpaper/Numix Blue Slack.jpg'

Also when I log into Opebox I have compton started with Openbox and I noticed it was no longer running, then I put in feh 2.19.3 and compton started running again ok when logging into Openbox.

I'm not sure what's happening here, but something in 2.22 is stopping compton from running.

I also start compton like feh from the ~/.config/openbox/autostart.sh;

```compton --config ~/.config/compton -b --logpath /tmp/compton.log```

-b as listed in ```man compton -  -b, --daemon```

Here's then the ~/.config/compton;

http://dpaste.com/1Z4T01K

**Comment by derf** [comment]
Yeah, I messed that one up. Fixed in 2.22.1, sorry :)

**Comment by sla0101** [comment]
LOL, no worries, you keeping me on my toes... :)

Keep up the good work...

Thanks
