### ISSUE TITLE
open url: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by lesavonfou** [derf/feh#343]
I got the following error whenever I try to reach imgur or redd.it:
```
feh WARNING: open url: SSL certificate problem: unable to get local issuer certificate
feh WARNING: https://i.redd.it/epxyy6f3cgwz.png - File does not exist
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
```
I am able to download this image with `curl` or `wget`. Have you any clue about what is going wrong?

**Comment by derf** [comment]
Could you check if edac0d1d056180ad7821ac21e09b2b53725b49f2 fixes this issue?

**Comment by lesavonfou** [comment]
Yup, this commit fix the issue!
Thanks.
