### ISSUE TITLE
On Scientific Linux it's build is broken

### ISSUE THREAD

**Issue by unixbhaskar** [derf/feh#348]
Followed this article https://jdhao.github.io/2017/05/06/install-feh-image-viewer-on-centos/
How to pass c99 flags to build it corretly?
`

bhaskar@ScientificLinux_19:23:18_Fri Dec 01:~/git-linux/feh>sudo make  -j${nproc} && make install
[sudo] password for bhaskar: 
make[1]: Entering directory `/home/bhaskar/git-linux/feh/man'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/bhaskar/git-linux/feh/man'
make[1]: Entering directory `/home/bhaskar/git-linux/feh/share/applications'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/bhaskar/git-linux/feh/share/applications'
make[1]: Entering directory `/home/bhaskar/git-linux/feh/src'
cc -g -O2 -Wall -Wextra -pedantic -DHAVE_LIBCURL -DHAVE_LIBXINERAMA -DPREFIX=\"/usr/local\" -DPACKAGE=\"feh\" -DVERSION=\"2.22.2\"   -c -o keyevents.o keyevents.c
cc -g -O2 -Wall -Wextra -pedantic -DHAVE_LIBCURL -DHAVE_LIBXINERAMA -DPREFIX=\"/usr/local\" -DPACKAGE=\"feh\" -DVERSION=\"2.22.2\"   -c -o wallpaper.o wallpaper.c
wallpaper.c: In function ‘feh_wm_set_bg’:
wallpaper.c:441:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int i = 0; i < cmdargc; i++) {
       ^
wallpaper.c:441:7: note: use option -std=c99 or -std=gnu99 to compile your code
keyevents.c: In function ‘feh_str_to_kb’:
keyevents.c:393:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (unsigned int i = 0; i < EVENT_LIST_END; i++) {
  ^
keyevents.c:393:2: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [wallpaper.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [keyevents.o] Error 1
make[1]: Leaving directory `/home/bhaskar/git-linux/feh/src'
make: *** [build-src] Error 2

`

**Comment by derf** [comment]
`CFLAGS=-std=c99 make`.

Try building the latest git version first though – feh now sets -std=c11 and some glibc feature test macros by default, this should fix your issue

**Comment by unixbhaskar** [comment]
Thanks, Daniel @derf  ..will give it a shot and let ya know.

**Comment by derf** [comment]
I'll assume it's working now, please re-open the issue if I'm wrong
