### ISSUE TITLE
The `--scale-down` option affects `--thumbnails` contrary to the man page description

### ISSUE THREAD

**Issue by lvanengelen** [derf/feh#351]
The man page says in the description of `--thumbnails` that `--scale-down` does not affect the thumbnail window, while in reality it does: whenever I click an image in the thumbnail window in my tiling window manager, the window resizes and the images are sized down. Pressing `*` (zoom to 100%) in the thumbnail window resizes them back. Removing the `--scale-down` option fixes this but disables down scaling for launched image windows.

The thumbnail resize is annoying but I prefer the `--scale-down` option enough to keep it in my config.

`themes` file:
```
feh --scale-down --auto-rotate

thumbs --thumbnails --thumb-width 256 --thumb-height 256 --limit-width 1600 \
       --sort filename --scale-down --auto-rotate \
       --fontpath /usr/share/fonts/TTF --font DejaVuSansMono/10
```
In my tests I use `thumbs` to open a thumbnail window. My feh version is 2.22.2 on Arch Linux.

**Comment by derf** [comment]
Indeed, thanks for pointing it out! The fix will be included in the next release.
