### ISSUE TITLE
Feature request: Slideshow config files

### ISSUE THREAD

**Issue by blackfyre** [derf/feh#354]
As with some highly configurable cli utilities I'd like the option to save my slideshow/feh preferences into a config file.
A main one in `~/.config/feh` which would serve as defaults, one in the target directory which supersedes the previous one and of course options supplied when starting `feh` would take precedence over all previously set options.

I could see that some of this is already in place with the Theme and Keys config from the `man` pages, if this is already in place then sorry for my ignorance, but I couldn't spot it in the `man`

**Comment by derf** [comment]
Hi!

I see where this can be useful, however, it also opens up a major box of headache: Assuming feh parses all options from a file in the current directory, this will include options executing user-specified commands, such as `--info`. So if a user downloads an archive from some shady place on the internet, extracts it, and uses feh to inspect its contents, we suddenly have arbitrary code execution.

I don't want to deal with this, so I'll stick with `~/.config/feh/themes`. Sorry.
