### ISSUE TITLE
PC crash on feh slideshow

### ISSUE THREAD

**Issue by JohnMartens** [derf/feh#363]
I'm having a PC with Ubuntu on it which I use to show JPG's in our tennis clubhouse.
The PC ia a HP with AMD 64 bits CPU and ATI graphics card

The feh slideshow starts correctly but after a while the PC crashes. This can be after one hour or sometimes after 12.
I thought that the problem was in ubuntu 16.04 an tried 14.04 (because of older hardware).
Problem is the same.
I tried to do a slideshow in Ristretto and that also gives me a PC crash.

I'm having a similar PC in the clubhouse showing feh slideshows for quite a few weeks.

Any idea how to solve this ?

John

**Comment by derf** [comment]
What exactly is crashing? feh (as in, you still have a running desktop and can simply restart the slideshow) or the entire PC?

**Comment by JohnMartens** [comment]
The entire PC
Even the On/Off button doesn't work anymore

Looks there is a memory leak, using the CPU/Mem monitor shows that memory consumption slowly rises. It is about 10 Mb an hour but crash seems to be way earlier that the left over 1000 Mb memory is consumed

**Comment by derf** [comment]
Which commandline are you using to start feh? Is feh consuming lots of memory or is it another application on your system?

**Comment by JohnMartens** [comment]
At startup I start a script which calls
feh -ZFY -R 30 -D 5 *.JPG
No other apps (besides the ubuntu basics) are startes at startup

The problem seems not to be related to feh itself but to showing al lot of JPG's
Also Ristretto makes the PC crach

John

**Comment by orbea** [comment]
@JohnMartens I would suggest trying to ssh into the computer from another device and then from root enter this command: `dmesg -w`. Then wait until your computer crashes again and hopefully dmesg will produce some useful output. You could also check your system logs and hope it was recorded in the past.

I suspect this is a hardware or kernel issue. You could try another stable distro like Slackware, if it persists I'd try looking for hardware failures.

**Comment by derf** [comment]
Closing this as there was no response for more than half a year.
