### ISSUE TITLE
Refresh current picture through a Signal

### ISSUE THREAD

**Issue by karatedog** [derf/feh#38]
In a non-slideshow mode SIGUSR1 or SIGUSR2 could be reused for refreshing the current picture. Now it just simply exits feh..
I use feh as a permanent image display for my projects where the results are bitmaps and I don't want to fiddle with console to run feh. 
Now I use the -R parameter but it would be much nicer just to send a signal when my application has just finished modifying the image -> this would help overcome that the -R parameter only accepts integers.

**Comment by renanwp2** [comment]
Is this feature still working?
