### ISSUE TITLE
Nested quoting for actions inside themes

### ISSUE THREAD

**Issue by FichteFoll** [derf/feh#381]
I want to define complex-ish actions for feh themes, but nested quotes don't behave well. It appears that they are ignored entirely and args are just split on spaces. Note that all these examples work fine if invoked from a terminal because the shell takes care of quotation there.

I would expect feh to just do a replacement on the variables and then pass the entire remaining string to the shell via `-c`.

## Reproduction

`~/.config/feh/themes`
```
test1 --action "[test] rofi -e 'this is a message: %f'"
test2 --action "[test] rofi -e \'this is a message: %f\'"
test3 --action "[test] rofi -e \"this is a message: %f\""
```

### Test 1

```sh
$ feh -Ttest1 same.png
feh WARNING: is does not exist - skipping
feh WARNING: a does not exist - skipping
feh WARNING: message: does not exist - skipping
feh WARNING: %f' does not exist - skipping
```

When running the action:
```
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
```

### Test 2

No error, but the popup displayed by rofi only shows `'this` instead of `this is a message: same.png`.

### Test 3

Same as with test 2, but showing `"this`.

---

```
[02-08][18:48:46] <derf0> feh_parse_options_from_string in options.c is probably the culprit
```

**Comment by derf** [comment]
fwiw, "foo \"bar\" ..." and 'foo \'bar\' ...' still don't work, but "foo 'bar' ..." and 'foo "bar" ...' do now. Fixing the former two would cause feh to start treating (and replacing) `\` as a special character in the themes config, potentially breaking backwards compatibility.
