### ISSUE TITLE
Description for --geometry seems to be wrong

### ISSUE THREAD

**Issue by 0xmatthias** [derf/feh#386]
I think the description for `-g` is not correct. From the manpage `-g, --geometry [width x height] [+ x + y]` the parameter width x height and +x +y are complete optional, that means `-g` without anything should be totally ok. However when I run
`$ feh -g ~/pictures/image.jpg`
feh tries to read all images in the actual directory instead of showing \~/pictures/image.jpg. My best guess is that feh interprets '~/pictures/image.jpg' as an argument for `-g`.
If I run `-g` with another option, then the next option is completely ignored, e.g.
`$ feh -g -d ~/pictures/image.jpg`
shows image.jpg, but doesn't print the filename.
However if I add another `-d`, e.g.
`$ feh -g -d -d ~/pictures/image.jpg`
then feh shows image.jpg and prints the filename.

**Comment by derf** [comment]
Indeed, that's misleading, `-g` requires at least one of width x height and +x+y to bet set. I'll updated the manpage to reflect this, thanks for pointing it out.
