### ISSUE TITLE
--slideshow-delay option not taken in account

### ISSUE THREAD

**Issue by monpelaud** [derf/feh#387]
Hi,
I'm using feh 2.18-2 with raspian stretch and I have an issue with --slideshow-delay option.
It seem's that the option --slideshow-delay is not taken into account when I also use --reload option, slideshow delay is random.
This issue did not exist with feh 2.12-1 with raspbian jessie.

Here is my command line:
/usr/bin/feh -Y --quiet --preload --recursive --full-screen --reload 5 /home/pi/Pictures/reload_photos/ --no-jump-on-resort --slideshow-delay 3 /home/pi/Pictures/start_photos/*.jpg

Best regards

**Comment by monpelaud** [comment]
Hi,
I increased the reload time and the projection time seems to be correct between two reloads but strongly impacted during every reload, much more than with version 2.12.1 of jessie.

Best regards

**Comment by ulteq** [comment]
Did you try removing the `--preload` flag? Do you really need it? How big is your image library? Did you try to increase the `--cache-size`? The default cache size is 4 MB. I would try something like 100 MB.

**Comment by monpelaud** [comment]
Hi,
First many thanks for your quick reply and your sugestions.
I'll try without --preload flag and by increasing the --cache-size.

Best regards

**Comment by monpelaud** [comment]
Hi,
With --cache-size flag I get this error message:
/usr/bin/feh: unrecognized option '--cache-size'
The flag --cache-size was introduced from the v2.23 and raspbian stretch uses the v2.18-2.
Anyway without the --preload flag it works fine.

Many thanks for your help.

Best regards
