### ISSUE TITLE
~/.fehbg is written with image's relative path as opposed to realpath.

### ISSUE THREAD

**Issue by xPMo** [derf/feh#389]
```
$ cd some/directory
$ feh --bg-fill some/image.png
$ cat ~/.fehbg
#!/bin/sh
'feh' '--bg-fill' 'some/image.png'
$ cd ~
$ ./.fehbg
feh WARNING: some/image.png does not exist - skipping
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
```

I have to fix ~/.fehbg every time I change background or write a wrapper which calls `realpath` on all the files.

I verified that this happens from a fresh build as well.  In fact, .fehbg will be written with the relative path to the `feh` binary if it was called that way.

**Comment by derf** [comment]
Yup, I overlooked that when fixing another fehbg-related bug. Will be fixed in the next release (due tomorrow)
