### ISSUE TITLE
Access viewport size (for its use in actions)

### ISSUE THREAD

**Issue by caradag** [derf/feh#391]
Hi, I want to create an action that will crop the image exactly as it appear in the current viewport. I can access the top left corner of the image (%o) and the zoom level (%z), but to compute the cropping parameters I need to access the width and height of the viewport. **Is that possible?**

**Comment by derf** [comment]
It will be in the next release (or now by building from git) using `%g`. I also added the `%Z` format specifier, which will give you the current zoom level at a higher precision.
