### ISSUE TITLE
Cannot scroll image with mouse scroll

### ISSUE THREAD

**Issue by inopia** [derf/feh#392]
I'm trying to bind following button configuration:

    # scroll the image with mouse scroll
    scroll_up 4
    scroll_down 5
    scroll_left 6
    scroll_right 7

However this doesn't work and the mouse just uses default configuration. I can bind mouse scroll to zoom so I know that I have the configuration file in the correct place.

feh version 2.25.1

**Comment by ulteq** [comment]
Placing your config into `~/.config/feh/buttons` works as expected on my system.

**Comment by derf** [comment]
You need to un-bind mousewheel up/down from prev_img/next_img first, like so:
```
# scroll the image with mouse scroll
prev_img
next_img
scroll_up 4
scroll_down 5
scroll_left 6
scroll_right 7
```

This is an unfortunate limitation of feh's current button and key handling code

**Comment by inopia** [comment]
Cool it works like this. Although you cannot scroll horizontally and vertically at the same time.
