### ISSUE TITLE
Recently feh drops the quotes around --image-bg in ~/.fehbg

### ISSUE THREAD

**Issue by aminb** [derf/feh#400]
I noticed that recently (in the last one or two versions) `feh` has started started dropping the quotes around `--image-bg`, which is particularly problematic if the argument is an html color code.

Running `feh --bg-center --image-bg '#272727' 'my-image.png'`, then `feh` writes this to `~/.fehbg`:

```sh
#!/bin/sh
feh --bg-center --image-bg #272727 'my-image.png'
```

If I further nest the `#272727` in quotes, on each invocation `feh` will drop one layer, until basically there's none left like above.

**Comment by derf** [comment]
Indeed, I'll address this in the next release. Thanks for pointing it out!

**Comment by aminb** [comment]
Cheers!
