### ISSUE TITLE
Feature Request: mixing various picture sources

### ISSUE THREAD

**Issue by joe-average-user** [derf/feh#401]
I find feh really nice for a rotating image display. But one thing is somehow missing. An option to mix various sources of images in one slideshow. Lets say:

feh -mix 5,1 /image-dir1 /image-dir2

Shows 5 images from /image-dir1, then 1 image from image-dir2, then next 5 from dir1, next 1 from dir2, and so on.
Of course you may choose option name as you like, but the basic idea behind would be very useful.
What do you think?

**Comment by derf** [comment]
Useful indeed, though not as a feh feature.

feh supports filelists and filenames on the commandline, so I suggest using/writing an external tool to generate such lists and pass them to feh. This way, other applications can benefit from the tool as well, so it's much more UNIX-y :)

**Comment by joe-average-user** [comment]
In your mind the file directories are "static", meaning the picture files inside the dirs are not changing (a lot). In my usage the number of files in one dir grows constantly whereas the other is static. So the idea is that feh cycles through all available files and then restarts from the beginning. Of course one can do that outside feh, but then, why using feh in such a situation at all? If I do the file list external, why not simply at a viewer command to the file list and execute it as script, completely without feh?
I think it would be a lot better to have a tool (feh) which can do it all in one... not?
