### ISSUE TITLE
feh freezes, spins when sent signal 15

### ISSUE THREAD

**Issue by giladogit** [derf/feh#405]
I use feh as part of a screensaver program. The program send signal 15 to remove feh. It works most of the time, but every so often it freezes and the only way to get it off the screen is killall -9 feh.

I attached a debugger to one such frozen instance

```
(gdb) bt
#0  0x00007fdc75f737c5 in _XReply () from /usr/lib64/libX11.so.6
#1  0x00007fdc75f6f4cd in XSync () from /usr/lib64/libX11.so.6
#2  0x00007fdc75f5122e in XCloseDisplay () from /usr/lib64/libX11.so.6
#3  0x000000000041249f in feh_clean_exit () at main.c:223
#4  0x00007fdc7592bc38 in ?? () from /lib64/libc.so.6
#5  0x00007fdc7592bc8a in exit () from /lib64/libc.so.6
#6  0x0000000000417987 in feh_handle_signal (signo=15) at signals.c:89
#7  <signal handler called>
#8  0x00007fdc759eadb4 in poll () from /lib64/libc.so.6
#9  0x00007fdc740d5902 in ?? () from /usr/lib64/libxcb.so.1
#10 0x00007fdc740d737f in ?? () from /usr/lib64/libxcb.so.1
#11 0x00007fdc740d74f1 in xcb_wait_for_reply64 () from /usr/lib64/libxcb.so.1
#12 0x00007fdc75f737f8 in _XReply () from /usr/lib64/libX11.so.6
#13 0x00007fdc75f6f4cd in XSync () from /usr/lib64/libX11.so.6
#14 0x0000000000412645 in feh_main_iteration (block=block@entry=1)
    at main.c:168
#15 0x00000000004059fa in feh_main_iteration (block=1) at main.c:61
#16 main (argc=16, argv=0x7ffc65d95e58) at main.c:86
```

BTW at the time this happens feh/x11 thread is spinning taking 100% of one core's cpu.

$ xdpyinfo | grep -i version
version number:    11.0
X.Org version: 1.19.6  

First I thought it was X11 bug and appened the above to 
https://bugs.freedesktop.org/show_bug.cgi?id=41870

But as they pointed out

> That's not a seperate thread, that's a signal handler that interrupted the
> same thread and made non-signal-safe calls.  That can never work and feh
> has to rewrite their signal handler not to do that.

**Comment by derf** [comment]
Fixed in #406 and included in feh 2.27.1.
