### ISSUE TITLE
--keep-zoom-vp does not preserve the viewport in 2.27 for images larger than the window unless freeze window size enabled

### ISSUE THREAD

**Issue by amaurea** [derf/feh#408]
In feh 2.27 --keep-zoom-vp no longer keeps the viewport fixed for images that are larger than the window (for example because the window has been clipped because it would otherwise be larger than the screen). For images like this, flipping to a new image will make the viewport jump back to the top-left corner of the image, just as if --keep-zoom-vp were not enabled. The old, much more useful behavior can be recovered by enabling "freeze window size" in the options, but there is no command line option that does this. The closest is --geometry, but that does not adapt to the first image opened like the old feh did.

I suggest either fixing --keep-zoom-vp to avoid the jumping behavior, or adding a new command line option that freezes the window size at the geometry of the first image (but still allows for manual resizing with the mouse, of course).

**Comment by ulteq** [comment]
I will take a look at it.

**Comment by amaurea** [comment]
@ulteq I'm having trouble reproducing this now. Either it's interacting weirdly with another issue, or I misunderstood what was going on.

When I wrote the bug report I was opening two images with the same shape that were both wider and taller than my screen. As far as I can remember, the window ended up being was tall as the screen (and hence shorter than the images). Flipping between the images would preserve zoom, but would cause the viewport to reset.

Sadly I'm not sure which image I did this with. When I test with similar images now, I experience something different. The window now ends up being some strange height that is shorter than both the image and the screen. Exactly how tall it ends up being seems to be a constant of the image size, but changes in a strange manner when varying the image size. Flipping between the images causes the window size to reset (if I had reshaped it manually), but both the zoom and viewport are preserved.

So things are still weird, but weird in a different way.

Perhaps things work correctly when whatever strange logic is being used to find the window height results in a window smaller than the screen, and that things only go wrong with the viewport when feh tries to make the window larger than the screen, and the window manager caps its size, or something.

I'm using the Muffin window manager, which is part of Cinnamon.

**Comment by amaurea** [comment]
I have tested a bit more, and made a series of images that illustrate what I see. I started by generating a 4096x4096 image, and then made a series of images with gradually smaller dimensions in the x-direction, y-direction or both at the same time, labeled xcut, ycut and xycut. Here are my observations:

1. The full-size 4096x4096 image xcut_0000.png opens into a window that is as tall as my screen, but not as wide as it. Excluding window decoration (that is, I let feh display normal windows with window decoration, but I measured the internal size since that was easier to get precisely), the window is 1080x1018.
2. For each 200 pixels I crop away in the x direction (corresponding to xcut_0200.png, xcut_0400.png, etc), the window width shrinks to 1027, 974, 921, ..., e.g. by 53 pixels. I would not expect the window size to shrink at all, since the image in all these cases is much wider than the screen.
3. For each 200 pixels I crop away in the y direction (corresponding to ycut_0200.png, ycut_0400.png, etc), the window width grows to 1135, 1196, 1265, 1342, ..., e.g. by first 55 pixels, then 61, then 69, then 77. Why would the *width* of the window change when the height of the window changes?
4. For each 200 pixels I crop away in both x and y at the same time, the window size is unchanged. Yes, this is strange in light of the x and y changes above not having the same size, but I've double checked it.
5. When selecting for instance xcut_0000.png and flipping between it and itself (e.g. feh xcut_0000.png xcut_0000.png) the viewport and zoom are normally preserved, except if I scroll all the way to the bottom of the image. If I flip between them then, the viewport moves upwards by 62 pixels, and then stays put there for subsequent flips.

You can find the images here: https://folk.uio.no/sigurdkn/feh_winsize

**Comment by ulteq** [comment]
This branch should fix 1 - 4: https://github.com/ulteq/feh/tree/fix-screen-clip
