### ISSUE TITLE
Try to use FEH as slide show

### ISSUE THREAD

**Issue by StefTan** [derf/feh#415]
Hello

I use FEH with next set of arguments:

feh -Z -F -R 60 -Y -d D 5 /home/pi/images

I have updated feh on my raspberry pi to version

2.27.1

Now I have the problem:
When I load a single file in the directory it is displayed correctly but when I load a second one it is not displayed. In the counts  I see the numbers updated but the picture showing is the initial single one.

Is there an option to fix this behavior (I want the timed show to start if there are picture added). If I go from 2 to 3 pictures all goes smooth and as expected

Stef Tan

**Comment by derf** [comment]
Is `feh -Z -F -R 60 -Y -d D 5 /home/pi/images` really the commandline you're using? Cause if it is, the fix is trivial: You made a typo and should use `feh -Z -F -R 60 -Y -d -D 5 /home/pi/images`

**Comment by StefTan** [comment]
Sorry that is a typo

Stef

**Comment by ulteq** [comment]
Do you remember which version you had installed before v2.27.1? I went back to v2.22.2 and it does not work either.
