### ISSUE TITLE
When opening an image with Feh, allow Feh to go to next/previous image?

### ISSUE THREAD

**Issue by ReneFroger** [derf/feh#420]
Let's assume we have a directory, called `images`.

In `images`-folder we have the following content:

    foo.jpg
    bar.jpg

When we call Feh with

    $ feh ~/images

It is able to view `foo.jpg` or `bar.jpg` when you're going to next/previous image.

But when you call Feh with the following command:

    $ feh ~/images/foo.jpg

Then feh is not able to display the next image in the same directory, when you use the key to go to the next image, in this case `bar.jpg`. I find that very frustating. Seems I'm not the only one with this issue, [as someone else asked the same question](https://bbs.archlinux.org/viewtopic.php?id=186060)

I wonder if there might be an option/a way to enable feh to go to next/previous image?

**Comment by ulteq** [comment]
Related with: https://github.com/derf/feh/issues/372

> I wonder if there might be an option/a way to enable feh to go to next/previous image?

Try the `--start-at` option.

**Comment by derf** [comment]
Hi!

You can now use `feh --start-at ~/images/foo.jpg`. This will show foo.jpg but also load all images in ~/images, so that you can navigate normally.
