### ISSUE TITLE
rand()/srand() calls should be random()/srandom()

### ISSUE THREAD

**Issue by Bandicoot** [derf/feh#427]
Problem:

Random image sequences aren't very random because of the RNG used and end up showing a particular subset of images.

Why:

Quoting from the BSD documentation, as the Linux docs don't mention this: 
> "The random() and srandom() functions have (almost) the same calling sequence and initialization properties as the rand(3) and srand(3) functions.  The difference is that rand(3) produces a much less random sequence -- in fact, the low dozen bits generated by rand go through a cyclic pattern.  All of the bits generated by random() are usable.  For example, `random()&01' will produce a random binary value."

Here is my patch:

[FEH-FIX.txt](https://github.com/derf/feh/files/2457654/FEH-FIX.txt)

**Comment by derf** [comment]
Indeed. glibc rand() actually behaves similar to random(), but there's plenty of other libc implementations out there. Thanks for pointing it out!
