### ISSUE TITLE
Building Feh on the Raspberry Pi Works Perfectly – Except Natural Sorting

### ISSUE THREAD

**Issue by zettabits** [derf/feh#431]
**BACKGROUND:** 
Version 2.18 of the outstanding image viewer feh is freely available to all Raspberry Pi users with Raspbian Stretch – the Raspberry's current operating system.  It can be obtained via the following command line:

sudo apt-get install feh

That version, however, is now 2 years old (released November 1, 2016).

I discovered that a major new enhancement has recently been added to feh with the release of version 2.25 on March 4, 2018.  From the changelog:

Add --version-sort option to enable natural sorting of file and directory
      names. This requires a libc with strverscmp support, which is a
      non-POSIX GNU extension.
.
.
**WHY IS THIS A BIG DEAL?**
For the first time, feh will correctly play the following images in proper order when using the brand-new "--version-sort" option:

1.jpg
2.jpg
10.jpg

Without the --version-sort option, there is no "natural sorting" capability for this _very common_ scenario.  As a result, the above images will play in this non-intuitive (and usually non-useful) order:

1.jpg
10.jpg
2.jpg

Of course, if someone already has their file names in a "computer-friendly" format with leading zeros, feh will play them in the correct order no matter what.  For example:

0001.jpg
0002.jpg
0010.jpg

But often, file names are simply not in that format – and a person may not wish to "destructively" rename all their files.

That's why feh 2.25 was a significant advance in image viewing!
.
.
**BUILDING FEH ON THE RASPBERRY PI:**
For those who would like to know, this is how you build the latest version of feh (version 2.28.1; released October 27, 2018).  I have personally verified that these steps work on all Raspberry model 3s:

**STEP 1:**  UNINSTALL ANY EXISTING FEH PACKAGE YOU MIGHT HAVE ON YOUR SYSTEM:
sudo apt-get --purge remove feh

**STEP 2:**  INSTALL THE DEPENDENCIES:
sudo apt-get install libcurl4-openssl-dev libx11-dev libxt-dev libimlib2-dev libxinerama-dev libjpeg-progs libpng-dev libexif-dev libexif12

**STEP 3:**  CREATE THE FEH BUILD FOLDER:
mkdir Feh_Build

**STEP 4:**  DOWNLOAD AND UNZIP THE LATEST STABLE RELEASE TARBALL:
cd Feh_Build
wget https://feh.finalrewind.org/feh-2.28.1.tar.bz2
tar jxvf feh-2.28.1.tar.bz2
cd feh-2.28.1

**STEP 5:**  COMPILE AND INSTALL FEH:
make -j4 curl=0 xinerama=0 verscmp=1
sudo make install
sudo ldconfig
.
.
**THE ISSUE:**
The above procedure creates a perfectly working copy of feh 2.28.1.  The only issue is that when I open Terminal inside a test folder of 3 JPEG images and run "feh --version-sort", feh still plays them in the following order:

1.jpg
10.jpg
2.jpg

Oddly, feh does NOT throw any error messages – such as "feh: unrecognized option '--version-sort'".  Instead, it fully accepts the option but simply ignores it and plays the images in the non-intuitive order of 1, 10, 2.

I noticed in the source code's README.md file that it says the following under the "available flags" section:

| verscmp | 1 | Support naturing sorting (`--version-sort`). Requires a GNU-compatible libc exposing `strverscmp` |

That led me to believe that MAYBE I needed to install the GNU Portability Library.  This does NOT come standard with Raspbian Stretch and must be installed via:

sudo apt-get install gnulib

Once I did that, a large batch of library files then became available on my system.  Here are all the ones related to "strverscmp" along with their full paths:

/usr/share/gnulib/lib/strverscmp.c
/usr/share/gnulib/modules/strverscmp
/usr/share/gnulib/doc/glibc-functions/strverscmp.texi
/usr/share/gnulib/m4/strverscmp.m4
/usr/share/gnulib/modules/strverscmp-tests
/usr/share/gnulib/tests/test-strverscmp.c
.
.
**MY QUESTION:**
Do I need to re-compile feh with an environmental variable to get it to properly recognize a "GNU-compatible libc exposing `strverscmp`"?

If so, exactly what command line should I use?

Or do I need to edit one of feh's source code files before I compile?  If so, what precisely would I need to change?

Thanks so much for any help you can provide!  Feh is a truly awesome program.

**Comment by derf** [comment]
Hi!

Glad you like feh!

`verscmp` needs to be enabled by setting a MAKE variable (which can also be an environment variable), but you already did that correctly by running `make -j4 curl=0 xinerama=0 verscmp=1`. So this is odd.

Could you give me the output of `feh --version` so we can make sure it was correctly enabled? I'll then see if I can reproduce the issue.

**Comment by derf** [comment]
Actually, nevermind that. I can reproduce that issue here. So there's nothing you did wrong, let's see if I can fix this.

**Comment by derf** [comment]
Short answer: You need to use `feh --sort name --version-sort`.

Long answer: `--version-sort` affects how the sort mode specified using `--sort` works, so if `--version-sort` is enabled but no sort mode is set, it has no effect. The documentation does not make this clear at all, so I'll update it to avoid such confusion. Thanks for pointing it out!

**Comment by zettabits** [comment]
Awesome job!  Natural sorting now works perfectly on the Raspberry Pi.

Believe it or not, after the PC and Mac, the Raspberry Pi is now the 3rd best-selling line of computers in the history of the world!  So I'm glad we could make feh run perfectly on it.

I have 3 quick questions and 1 quick thought:
.
.
**QUESTION 1:**
As you know, while troubleshooting this issue, I installed the GNU Portability Library.  This does NOT come "standard" with the Raspbian operating system.  Should the gnulib package therefore be added to the dependencies I listed in Step 2 of my compiling instructions?  Or is feh's source code already providing whatever strverscmp-related items it needs?  I just wanted to make sure that other Raspberry users who see this exchange in the future will have a successful build that includes natural sorting.
.
.
**QUESTION 2:**
In the man pages for version 2.28.1, I see this:

_For sort modes other than name, filename, dirname, or mtime, a preload run will be necessary, causing a delay proportional to the number of images in the list._

Will a preload run also apply to natural sorting?  For example, if someone has tens of thousands of images in a folder, will natural sorting first trigger a considerable delay before it displays the first image?  If so, this is perfectly understandable.  I'm just wondering.
.
.
**QUESTION 3:**
When it comes to feh's behavior, what's the difference between sorting by "name" vs. "filename"?  If I had to speculate, I would guess that "name" ignores the extension, whereas "filename" includes it – so that 1.jpg would come before 1.png?  I looked through the documentation, but I don't see any reference to this topic.
.
.
**QUICK THOUGHT:**
At the moment, natural sorting requires the somewhat long and hard-to-remember syntax:

feh --sort name --version-sort

Perhaps in a future version, it could be made simpler and more consistent with the existing syntax.  For example, here's how it could look along with some of the existing sort modes:

feh -S natural

feh -S width

feh -S mtime

feh -S mtime --reverse

Thanks again for the outstanding job you've done on this great program over the last 8+ years.  In my opinion, feh is easily the FASTEST and most robust image viewer I've ever encountered on the Linux platform.

**Comment by derf** [comment]
On Sun, Nov 04, 2018 at 03:36:39AM -0800, zettabits wrote:
> As you know, while troubleshooting this issue, I installed the GNU Portability Library.  This does NOT come "standard" with the Raspbian operating system.  Should the gnulib package therefore be added to the dependencies I listed in Step 2 of my compiling instructions?  Or is feh's source code already providing whatever strverscmp-related items it needs?  I just wanted to make sure that other Raspberry users who see this exchange in the future will have a successful build that includes natural sorting.

It's not needed, strverscmp is provided by the GNU C library, which is
already available on Raspbian. It's a non-standard extension and may not be
available in other C libraries (e.g. on BSD), hence the `strverscmp` flag.


> In the man pages for version 2.28.1, I see this:
> 
> _For sort modes other than name, filename, dirname, or mtime, a preload run will be necessary, causing a delay proportional to the number of images in the list._
> 
> Will a preload run also apply to natural sorting?  For example, if someone has tens of thousands of images in a folder, will natural sorting first trigger a considerable delay before it displays the first image?  If so, this is perfectly understandable.  I'm just wondering.

No, natural sorting does not need a preload run.

> When it comes to feh's behavior, what's the difference between sorting by "name" vs. "filename"?  If I had to speculate, I would guess that "name" ignores the extension, whereas "filename" includes it – so that 1.jpg would come before 1.png?  I looked through the documentation, but I don't see any reference to this topic.

"name" is the path (e.g. photos/123.jpg if you run "feh photos"), whereas
"filaneme" only refers to the file's name (e.g. "123.jpg").

> At the moment, natural sorting requires the somewhat long and hard-to-remember syntax:
> 
> feh --sort name --version-sort
> 
> Perhaps in a future version, it could be made simpler and more consistent with the existing syntax.  For example, here's how it could look along with some of the existing sort modes:

I'll think about it. feh already has way too many options, so I try to avoid
adding new ones.

**Comment by kenmk** [comment]
I have just followed the instructions above to install feh on my Raspberry Pi 3B+ and they just work.  The only change I made was to get the latest (at this time) version 3.1.3 to be able to use the "--on-last-slide" option to run through a set of directories from a script.
