### ISSUE TITLE
Add .avif (AV1 Image File Format) support

### ISSUE THREAD

**Issue by EwoutH** [derf/feh#437]
The AV1 Image File Format (AVIF) is a new image format based on the AV1 video codec. It would be great if support for this format could be added.

The AVIF spec can be found here: https://aomediacodec.github.io/av1-avif/
Netflix published a bunch of test images: http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/

**Comment by derf** [comment]
Hi!

feh relies on Imlib2 and (as fallback) ImageMagick as loaders and does not contain file format-specific code itself. Please direct your issue to one of those libraries, preferably Imlib2.

**Comment by vi** [comment]
Created basic loader for avif: https://github.com/vi/imlib2-avif

Although:

* May require a bit of hacking to actually build and install
* Alpha channel not tested yet
* Only 8-bit input images

**Comment by Daniel451** [comment]
@vi any updates on this?

**Comment by vi** [comment]
@Daniel451, No.

Are avif images really used in practice? Have you tried imlib2-avif? If yes, does it work? If yes, what more features do you need?

**Comment by chrboesch** [comment]
AVIF-Images work and become more relevant. When I try to open with feh, I get the warning "Does not look like an image (magic bytes missing)"

**Comment by eworm-de** [comment]
Opened #643 to accept AVIF file format. For me this works when `imlib2-heif` (https://github.com/arp242/imlib2-heif) is installed.

**Comment by eworm-de** [comment]
A heif loader has been merged in imlib2 upstream:
