### ISSUE TITLE
Configuration-File for Options

### ISSUE THREAD

**Issue by astier** [derf/feh#445]
## Problem
Options can only be set temporarily via the command-line and have to be specified each time explicitly when feh is called.

## Request
Feh should read a config-file *~/.config/feh/options* at each start and use the specified options which are defined in the respective file as parameters.

**Comment by derf** [comment]
Hi!

Actually, that's already possible: Create a "feh" theme in `~/.config/feh/themes`, e.g. `echo "feh --verbose" > ~/.config/feh/themes`. Now, each time you start feh, it will automatically use `--verbose`.

**Comment by astier** [comment]
Wow. Thank you. Very cool.
