### ISSUE TITLE
Run ~/.fehbg overwrite file ~/.fehbg itself

### ISSUE THREAD

**Issue by balalaXD** [derf/feh#456]
File ~/.fehbg
```bash
#!/usr/bin/env bash

feh --bg-scale --randomize /media/HDD/wallpapers/

```

Running `~/.fehbg &` first time works, but run again complaining:
```bash
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
```

Open the `~/.fehbg`:
```bash
#!/bin/sh
feh --bg-scale
```

Version:
```
feh version 3.1.1
Compile-time switches: curl exif help stat64 verscmp xinerama
```

**Comment by balalaXD** [comment]
But with specific image it works all the time
```bash
#!/usr/bin/env bash

feh --bg-scale --randomize /media/HDD/wallpapers/desert.jpg
```

i guess the bug come from option `--randomize`

**Comment by derf** [comment]
Hi!

Yup, that's a bug which (probably) occurs whenever feh's background setting mode is passed at least one directory argument. I'll look at it as soon as I have some time.

**Comment by DuBistKomisch** [comment]
just updated to 3.1.2 on arch and this still seems to happen

```
 $ feh --version
feh version 3.1.2
Compile-time switches: curl exif help stat64 verscmp xinerama
```

**Comment by DuBistKomisch** [comment]
Guess I should include my command... it's `feh --bg-fill --no-xinerama ~/sync/images/wallpapers/qjkoROd.jpg`

**Comment by derf** [comment]
Yup, my bad. I introduced a new issue while fixing the directory/randomize problem. It should be fixed now, can you confirm that from a git checkout?

**Comment by DuBistKomisch** [comment]
@derf can confirm my command works with fehbg on master :+1:
