### ISSUE TITLE
Cannot make -x action work

### ISSUE THREAD

**Issue by dingdongbannu** [derf/feh#461]
I'm pretty new to this so me being an idiot might be the real issue here, but I always get an error message when trying to make actions work.

I open the image with feh --action1 -x imagename.jpg
When pressing 1 I get this message in the terminal: 

sh: 0: -c requires an argument

Also, I was wondering how to apply said action, when not starting Feh with a terminal, but directly opening an image with Feh per "open with...".
I'm fairly certain there's something I'm doing fundamentally wrong, but I cannot figure out what... Help would be really appreciated.

**Comment by derf** [comment]
You need to specify the action to execute after `--action1`  :)

E.g. `feh --action1 "echo %F" -x imagename.jpg` -> feh will print the filename on the terminal when you press 1.

If you want to have actions when feh isn't started from a terminal, you can edit ~/.config/feh/actions and provide a "feh" theme. Basically, add the following line:

```
feh --action1 "echo %F"
```

(with the appropriate action command)

Note that this action will be available for all feh instances, you can't selectively enable/disable it in this setup.
