### ISSUE TITLE
transparency

### ISSUE THREAD

**Issue by selr** [derf/feh#470]
Hi,

Is it possible to display a png with the transparent part of the png really transparent in fullscreen? 
I mean:
**My wallpaper is like this**
![wallpaper](https://user-images.githubusercontent.com/29476513/56613230-7f25ad00-6616-11e9-9fad-40e696de2a4f.png)

**My png is like this**
![aa](https://user-images.githubusercontent.com/29476513/56613291-9ebcd580-6616-11e9-9bcf-f4a87a351e60.png)

**The result I would like is like this**
![result](https://user-images.githubusercontent.com/29476513/56613460-f6f3d780-6616-11e9-96b5-0b55b167d5cc.png)

**But it's like this for the moment:**
with the following command
` feh --fullscreen /path/1.png`
![not_result](https://user-images.githubusercontent.com/29476513/56613570-35899200-6617-11e9-8dd9-56d4daa1d9a9.png)

Thanks for the amazing job :D

**Comment by derf** [comment]
Hi!

Sorry, that's not possible and out of the scope of feh's intended feature set. If you always have the same background image (or know the file in which the current background image is located), you can do this yourself by combining the two images with [ImageMagick](https://www.imagemagick.org/) and displaying the result in feh.
