### ISSUE TITLE
howto redirect input to feh via fifo pipe

### ISSUE THREAD

**Issue by IpPsar01** [derf/feh#474]
Some help is needed on the following:
I would like to fork feh as a slideshow in the background and still be able to sent some keys to it (eg. 'n' for next picture or 'q' to quit).

So I created a pipe: mkfifo /tmp/cmdVideo
I exported DISPLAY=:0
and start: feh -Z -z -F -d -D10 -f /home/pi/newapp/AlleFotos </tmp/cmdVideo &

Via another shell I sent characters into the pipe:
To actually start feh: echo -n . > /tmp/cmdVideo
After that it starts showing pictures.

All my other characters don't arrive at feh. Eg.:
echo -n 'n' > /tmp/cmdVideo
echo -n 'q' > /tmp/cmdVideo
Feh just goes on showing pictures.

I have also tried to move the location of the '</tmp/cmdVideo' within the commandline but that did not help.
Obviously I am making a mistake here. Can someone help me in how to set this up correctly?

The same setup works fine for omxplayer (characters come through however it plays at speed 2.0 when using input via a pipe!). 

Thanks in advance!

**Comment by derf** [comment]
Hi!

You're doing everything right, Pipe input just isn't supported by feh. At the moment, it can only be controlled by X11 or terminal input (which must be input on the terminal that started feh and cannot be redirected). I'll try to clarify this in the documentation.

I'm aware that proper remote controls for feh are very useful for slideshow displays, digital signage and the likes. Until I get around to implementing them, please use the XTest extension to send key events directly to the feh window. Perhaps you can already do most of the stuff you need with SIGUSR1 and SIGUSR2.
