### ISSUE TITLE
Open SVG without --conversion-timeout

### ISSUE THREAD

**Issue by mb720** [derf/feh#475]
Hi and thanks a lot for feh!

I'm using feh 3.1.3 on Arch Linux 5.1.7.

As suggested in the [Arch Linux Wiki](https://wiki.archlinux.org/index.php/Feh#Open_SVG_images), I open SVG images like this:

    feh --conversion-timeout 1 file.svg

Without the `--conversion-timeout` part, I run into this error:

>feh: No Imlib2 loader for that file format

I was wondering if there's a way to have feh open SVGs without having to specify `--conversion-timeout` (except creating a Bash alias).

Thanks!

**Comment by derf** [comment]
Hi!

You can configure feh to always use that option by specifying it in a theme config, like so:

`echo "feh --conversion-timeout 5" > ~/.config/feh/themes`

This will create a "feh" theme, which will be loaded by default and which will automatically apply the conversion-timeout option.
