### ISSUE TITLE
~/.fehbg cleared when there are no monitors

### ISSUE THREAD

**Issue by Streetwalrus** [derf/feh#482]
I use a DisplayPort monitor. Turning the screen off pretty much equals to disconnecting the cable, so I suspect this is the trigger for this issue.
When my session starts with the monitor off, feh (understandably) fails to set the wallpaper, but it also silently (I've tried to capture a log but the file came out empty) replaces my .fehbg with just `feh --bg-fill` (no file path). This means I have to fix it manually every time it happens.

I don't know if writing an empty file in this case is intended behavior (when invoked manually), but in my opinion, the `--no-fehbg` option should be included in the fehbg file itself, as there's no point in rewriting the same thing every time, and configuration files shouldn't spontaneously change either.

**Comment by derf** [comment]
That is an excellent point. I have added --no-fehbg to the .fehbg command line, thanks!

**Comment by Streetwalrus** [comment]
Thanks!
