### ISSUE TITLE
Centos7 fails to compile feh

### ISSUE THREAD

**Issue by Phibonacci** [derf/feh#485]
Centos7 is using libcurl v7.29 but CURLOPT_XFERINFOFUNCTION was added in v7.32.0

See the following similar error from psql-http: https://github.com/pramsey/pgsql-http/issues/62

> In file included from /usr/include/curl/curl.h:2238:0,
>                  from imlib.c:40:
> imlib.c: In function ‘feh_http_load_image’:
> imlib.c:618:27: error: ‘CURLOPT_XFERINFOFUNCTION’ undeclared (first use in this function)
>     curl_easy_setopt(curl, CURLOPT_XFERINFOFUNCTION, curl_quit_function);
>                            ^
> imlib.c:618:27: note: each undeclared identifier is reported only once for each function it appears in
> make[1]: *** [imlib.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make: *** [build-src] Error 2

**Comment by xQsme** [comment]
https://serverfault.com/questions/321321/upgrade-curl-to-latest-on-centos

**Comment by derf** [comment]
Fixed. Thanks for the pointer to the pgsql-repo!
