### ISSUE TITLE
[Feature request] Ability to switch through images when just opening one image.

### ISSUE THREAD

**Issue by LichenSymbiont** [derf/feh#486]
Oh, or make "--start-at ~/images/foo.jpg" more obvious.
Because last time I checked out Feh, I didn't even know it could flip through images in a directory!
I thought it was just for opening one image at a time, and being as light-weight as possible.
An easy misunderstanding if you're just installing it through a distribution.

**Comment by Ferada** [comment]
What exactly are you asking for? It's pretty discoverable that `feh` will e.g. show the current working directory, `man feh` also says `feh [options] [files | directories | URLs ...]` right at the top ...?

**Comment by derf** [comment]
When did you last check out feh? Nowadays, the `feh.desktop` file provided by feh (and used by distros) already includes `--start-at`, so if you start feh through a file manage you will automatically be able to flip through other images.

As for commandline usage, I'm with @Ferada: I think it's fairly obvious that feh supports more than just single file arguments. Could you elaborate why you think that's an issue?

**Comment by LichenSymbiont** [comment]
What I mean is that feh is just one of many minimal image viewers, and when people are testing out different image viewers through their distro repos, they don't expect to have to read the man-pages to get the program to behave like every other image viewer in the whole bloody universe, lol.

**Comment by derf** [comment]
I get your point, but don't consider it to be enough of an issue to justify changing feh's default behaviour (which most likely would break someone else's workflow and thus also lead to issues). Closing this as wontfix.

Nevertheless: Thank you for taking the time to report this.

**Comment by LichenSymbiont** [comment]
Cool. But do consider making "--start-at image-name" more obvious. And I don't get how it could break someones defaults by being able to switch between other images in the opened images folder. Sure, it does take some extra disk and CPU operations to make a list of all image files in the directory, but that may be remedied by doing the listing after opening the first image. In fact that's always a good program-flow decision: to load the minimal amount of stuff and present the main stuff to the user as fast as possible, and load the extra stuff later.
