### ISSUE TITLE
can't open tga images with palette

### ISSUE THREAD

**Issue by rofl0r** [derf/feh#491]
here's an example file https://0x0.st/zgB4.tga

it seems handling of  TGA_TYPE_MAPPED is entirely missing in imlib2

**Comment by rofl0r** [comment]
patch is available here https://github.com/sabotage-linux/sabotage/blob/c4f1fe5307dd21bd53d17c51f32049092d6c9d34/KEEP/imlib2-tga-palette.patch

**Comment by Ferada** [comment]
Since I've now done that myself (and there's a bit of setup involved), I can get it submitted to Imlib2 for you, @rofl0r, is that okay?

**Comment by rofl0r** [comment]
i updated the patch with some security code so we don't end up in an unexpected code path when bpp != 8:
https://github.com/sabotage-linux/sabotage/blob/master/KEEP/imlib2-tga-palette.patch

> Since I've now done that myself (and there's a bit of setup involved), I can get it submitted to Imlib2 for you, @rofl0r, is that okay?

that would be really nice! i struggled myself to get an account for phab.e

> The case marked as /* currently not supported */ is what, anything other than the 3/4 component case?

right. tga seems to support[0] 16bit with 5551 encoding, but there is currently no support in imlib for it at all, and 8 bit with 8 bit palette doesn't really make sense anyway.

[0] http://www.paulbourke.net/dataformats/tga/

**Comment by rofl0r** [comment]
meanwhile i updated my patch to support palettized RLE-compressed pics too
(took me 5x longer than needed due to gnu-style indentation...)

**Comment by Ferada** [comment]
@rofl0r apropos formatting, is https://github.com/sabotage-linux/sabotage/blob/c4f1fe5307dd21bd53d17c51f32049092d6c9d34/KEEP/imlib2-tga-palette.patch#L73 this correctly formatted? I genuinely do not know the rules about that particular style enough to say.

**Comment by rofl0r** [comment]
> correctly formatted? I genuinely do not know the rules about that particular style enough to say.

me neither :) looks like we'll have to wait for complaints...

thanks!

**Comment by rofl0r** [comment]
patch against latest git is available here https://0x0.st/zEzS.patch

**Comment by rofl0r** [comment]
@Ferada would you please mention to kwo on the bugtracker that i fulfilled his request with the above patch ? or maybe you just send him here so i can interact with him directly.

**Comment by Ferada** [comment]
Yes, updated. I ran `indent` as requested which made two minor changes, but I'll let them decide if that's worth it or not.

**Comment by Ferada** [comment]
@rofl0r merged, please go ahead and verify this works for you then.

**Comment by rofl0r** [comment]
thanks for your help! it works as expected, also with RLE compressed variant (e.g.: https://0x0.st/z6ZY.tga )
