### ISSUE TITLE
videos option for feh

### ISSUE THREAD

**Issue by warhansen** [derf/feh#502]
Firstly, I love feh. I use it at home to randomly display the 26 000 odd photos I have taken over the years and I have remembered some real good times.

I would like to know if there is any future plans to include videos. It can be very basic, maybe even with no resizing etc. 

Any chance?

Thanks guys for the awesome work so far!

**Comment by Ferada** [comment]
Why'd you need video support in the first place? There's already excellent options like `mplayer` / `mpv`, `vlc` (and probably a bunch more), all of which have a variety of options, great support for about any format and can be scripted / remote-controlled.

**Comment by warhansen** [comment]
I want to play photos and when they are next in que then videos, all from
the same program.

I don't want to just play videos or just photos. So if randomly a video
comes up I want it to be played and if a photo comes up next it must be
displayed.

I cannot find any other player thst can rondomly play photos which is why I
love feh!

Thanks.

**Comment by cantandwont** [comment]
@warhansen _mpv_ works for this. Although how it opens files from a file-manager is different to feh (there's no "--start-at" option).

When I want to do something like you're describing I just select relevant files/folders, open an mpv window, then drag & drop (with Shift key pressed to append to the playlist).

However to automate this (like feh's "--start-at"), there's an lua script to add other files in the same directory to the "playlist" automagically: https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua

In conjuction with the option `--loop-playlist`, this should make using mpv a bit more like feh.

**Comment by derf** [comment]
Hi!

As pointed out by @cantandwont, mpv seems like the better solution for this use case. It should also be possible to write a wrapper script which uses feh for static and mpv for animated slideshow elements.

Regarding your question: There are no plans for video support. feh will continue to be limited to (static) images.
