### ISSUE TITLE
--image-bg does not read XColor codes unless "#" character is escaped

### ISSUE THREAD

**Issue by invokah** [derf/feh#506]
Hi,

unmentioned in the man page, --image-bg will not accept an XColor code unless the "#" symbol at the beginning is escaped, like "\#".  When using feh for a background, it would be nice to know this information.

**Comment by derf** [comment]
Hi!

That's a shell issue: some shells might use `#` as comment or otherwise special symbol, so you need to escape it to stop the shell from handling it. feh itself must receive a literal `#`.
