### ISSUE TITLE
Can't get captions to work as documented...

### ISSUE THREAD

**Issue by fpp-gh** [derf/feh#519]
Hi,

I'm truly sorry for opening an issue, probably just because of my lack of understanding.
I'm dug deep down into a photo frame project for my old mother : it's Linux-based of course (raspberry Pi), and feh is a good match for that in slideshow mode.
It took some time experimenting with the many options, but I now have something that works.

Except for the caption issue, that is...

I have something like 31K image files (including the caption .txt files) in over 800 folders (including the caption subfolders).
Using Python scripts I have created the many caption subfolders and the many txt files named after the images for the captions.

However, the slideshow still stubbornly does not display my captions, and shows the full path of the current image on top instead, which is quite ugly and not very useful.
Surprisingly, if I hit 'C', the string displayed beneath the image for editing is the one in the corresponding txt file in the caption subfolder. But I'm not going to do that for all of them :-)

What I'd expected was to have the caption file content displayed on top of each image, and nothing more, is that not possible ? Are there unwritten conditions for caption overrides to work ? (such as no whitespace or non ASCII characters, etc. ?)

My current launcher command is : 
/usr/bin/feh -d -r -z -x -Z -Y -FD6 -K "caps" --auto-zoom /media/pi/pix

Am I doing something wrong, or misunderstanding some important switch ?

Thanks for any hints, and sorry for pestering...

Best,
FP

**Comment by fpp-gh** [comment]
Okay, so I guess I must apologize yet again, seems I was really tired yesterday evening after staring at feh slideshows all day :-)
For some reason I was fixating on seeing my captions appear at the top instead of the full image path, and I realized this morning that they did appear at the bottom -- but not all folders have their captions filled in yet, so it was easy to miss...
Next step was removing '-d' from the command line :-)

**Comment by fpp-gh** [comment]
Er, famous last words...
Is there a way to avoid images less wide than the screen being stretched horizontally ?
TIA,
fp

**Comment by fpp-gh** [comment]
Goodbye, and thanks for all the fish !

**Comment by derf** [comment]
Sorry for the late reaction – I still manage to be quite busy despite lockdown and all. How exactly are your images being stretched? feh shouldn't change image aspect rations by itself.

Regarding the accented characters: unfortunately, feh's unicode support is... mostly lacking. So non-ASCII characters may work or not; combined with a rather limited glyph set in its default font that makes lots of room for things to go wrong. For a start, you could check whether another font (see `--font` and `--fontpath`) works better for you.

**Comment by fpp-gh** [comment]
Hi, thanks for chiming in !

The encoding issue is now moot : I just eliminated all the non-ASCII characters :-)
Text only appears briefly as image captions, so it wasn't a hard decision.

The stretching issue[s] seems more complex, a combination of cases :
* recent digital pictures, with a resolution far above the display's, look mostly all right

* old pictures (digital from late 90s to before 2010, depending on my camera of the day, and also homemade scans of much older stills and negative films ) tend to have lower resolution than our current monitors, and they suffer most : portrait mode is not too bad, but in landscape they tend to be visibly stretched from side to side, with some pixellation and a lot of waist size ballooning :-)

* Another (rare but extreme) case is when a picture that should display in portrait ends up as landscape for some reason I don't understand (EXIF ?) : what should have fit inside the monitor height is now stretched all the way to its width... I don't get why/when/how feh decides to do this :-)

I hope the above is not too fuzzy, if there is any info I can provide, or experiment I can try, just ask.
For a start, my feh launcher has currently been changed to this: 
/usr/bin/feh -d -r -z -x -Z -Y -FD6 -K "caps" --auto-zoom /media/pi

TIA,
fp

**Comment by derf** [comment]
Hi,

On Thu, Apr 09, 2020 at 11:48:28AM -0700, fpp wrote:
> * old pictures (digital from late 90s to before 2010, depending on my camera of the day, and also homemade scans of much older stills and negative films ) tend to have lower resolution than our current monitors, and they suffer most : portrait mode is not too bad, but in landscape they tend to be visibly stretched from side to side, with some pixellation and a lot of waist size ballooning :-)

You can combine `--auto-zoom` with `--zoom PERCENT` to limit the maximum zoom,
like so:

```
feh --auto-zoom --zoom 100 /media/pi
```

If an image is larger than the screen, it will be scaled to fit -- if it is
smaller, it will be shown at original size and surrounded by black borders.

The 100 means 100%, so you can also use e.g. 150 to zoom images by at most
1.5x.

> * Another (rare but extreme) case is when a picture that should display in portrait ends up as landscape for some reason I don't understand (EXIF ?) : what should have fit inside the monitor height is now stretched all the way to its width... I don't get why/when/how feh decides to do this :-)

If your feh is compiled with EXIF-support enabled (check `feh --version`),
you can use `--auto-rotate` to make feh automatically rotate images based
on EXIF data.

> For a start, my feh launcher has currently been changed to this: 
> /usr/bin/feh -d -r -z -x -Z -Y -FD6 -K "caps" --auto-zoom /media/pi

FWIW, this is a bit redundant: `-Z` and `--auto-zoom` are the same :)

Regards,
Daniel

**Comment by fpp-gh** [comment]
Yeah, those man pages are not for the faint of heart with bad short-term
memories :-)

Yesterday evening I spent some time trying to obtain a screenshot of a
stretched image as displayed in feh, so that you could compare it with the
original. Up to now, unfortunately, the snapshots show the original image,
not the display (with ImageMagick at least). Maybe because the feh "window"
is a separate buffer ?
As usual with Linux there are tons of screenshot apps available, if you
know of one that works with feh I'll be happy to try that...
Best,
fp

**Comment by derf** [comment]
ImageMagick's `convert` does everything right AFAIK. If the screen is stretched, but the screenshot isn't, this is likely a screen configuration issue – feh can't do anything about that. To determine whether that's the issue, you could check whether fonts or other applications also look stretched on your screen.

**Comment by fpp-gh** [comment]
Tried again today, and still a mystery to me...

It's not just feh that stretches some pictures, but all the image viewers I've tried.
I've managed to get some screenshots of those, and viewing the captures shows the same as the original.
However, if I transfer the captures to a Windows machine, image viewers display the right aspect ratio!
This baffles me.

I think I'm gonna have to take a photograph of the image on screen for you to believe me :-)

**Comment by fpp-gh** [comment]
Okay, so here is one original picture from 1998 that is just 1024px wide :
[image: feh_001462_000001_1998-06-26 @ 06-19-14.jpg]

And here is how it is displayed, no matter what, by the raspberry using the
"Debian Buster with desktop" image.

It's a photo of the screen so quality is bad, but just look at that bottle
and the head of my son :-)

What kind of "screen configuration issue" could induce this ?...

**Comment by fpp-gh** [comment]
Ooops... did you get the attachments with the mail ? :-)

**Comment by derf** [comment]
The image didn't make it through GitHub, sorry. But I can take a guess.

Your RasPi might have different assumptions about the display size than the display itself. If you have a 16:9 screen, but Raspbian thinks it's 4:3, it will not send the amount of horizontal pixels the screen expects – which it may respond to be stretching the image horizontally. Likewise for the inverse case (vertical stretching)

See if you can find an image of a square and open it with a browser. If you don't see a square on the screen, that's the problem.

I'm not an authority on Raspbian and (possibly obscure) screen configurations, but a look at `xrandr` and a comparison with your screen's resolution might already provide a clue.

**Comment by fpp-gh** [comment]
Ahaha, stupid me, thanks for the heads-up !!
I was so focused on the software part (feh and its command line, startup script etc.) that I totally forgot about the usual settings for a new raspberry in /boot/config.txt ... and I've played with quite a few raspis, so it's not like I shouldn't know :-)
The defaults were not appropriate for my monitor of course, so after correcting them and a few reboots, things were much improved : I put zooming back in and the aspect ratio is now perfect for all image sizes and ages :-)
So nothing to do with squares or Debian or LXDE, just my usual stupid self :-)
Thanks for putting up with that !

PS: are transitions between pictures somewhere on the rodamp ? :-)
