### ISSUE TITLE
auto-reload seg fault

### ISSUE THREAD

**Issue by brewerja** [derf/feh#521]
Compiling from source on Ubuntu 18.04.4, feh 95da90a:
`make xinerama=0 curl=0 inotify=1`

If I open a file: `feh file.png` then I rewrite the file underneath to trigger auto-reload, I get a seg. fault at line 122 of `gib_hash.c`:

```
#0  0x000055555555f568 in gib_hash_get (hash=0x0, key=0x55555578d550 "/path/to/file.png") at gib_hash.c:122
#1  0x0000555555561f48 in feh_reload_image (w=0x55555579a100, resize=0, force_new=0) at imlib.c:379
#2  0x000055555557dd0b in feh_event_handle_inotify () at winwidget.c:746
#3  0x000055555556acdc in feh_main_iteration (block=1) at main.c:234
#4  0x000055555556a42a in main (argc=2, argv=0x7fffffffd518) at main.c:100
```

I know just enough to run `gdb` and see that the hash is null.

**Comment by derf** [comment]
Right you are. There's a missing null pointer check as the cache may not be initalized yet.

Thanks for reporting!
