### ISSUE TITLE
[Feature Request] Add environment variable or config file option to disable .fehbg

### ISSUE THREAD

**Issue by redmosaic** [derf/feh#528]
I want option to completely disable creation of .fehbg file whenever i invoke it through file manager or from shell script.

**Comment by derf** [comment]
Hi!

feh supports themes and theme-specific default options. Write the following line to `~/.config/feh/themes` to entirely disable fehbg creation:

```
feh --no-fehbg
```

If you want to disable it when feh is run from file manager or shell scripts, but leave it enabled when you run feh from the terminal, you have two options:

* change feh.desktop and your shell scripts to use `--no-fehbg`
* add `feh --no-fehbg` to `.config/feh/themes` (see above) and use `feh -T none` or `feh -T ''` in the terminal. You can hide that behind a shell alias so you only have to type `feh`

Let me know if that doesn't work for you.
