### ISSUE TITLE
[Feature request] Make feh use a default theme and allow customizing that theme

### ISSUE THREAD

**Issue by duongdominhchau** [derf/feh#529]
I can create a theme and use it with `--theme <name>`. However, I have no way to customize `feh` behavior when it is run without any command line options.

I suggest making `feh` search for a theme named `default` first and use it before falling back to default values for its options.

Currently, to change `feh` default behavior, I have to append `--theme <name>` to the `Exec` of `feh.desktop`, the original desktop file is useless.

**Comment by derf** [comment]
Hi!

There is a default theme – see the feh manual, section "-T / --theme":

"The theme can also be set via the program name (e.g. with symlinks), so by default feh will look for a "feh" theme."

So just create a "feh" theme and you're good to go.
