### ISSUE TITLE
feh rotates and flips lossy and looses exif data

### ISSUE THREAD

**Issue by reald** [derf/feh#532]
# Steps to reproduce:

```
$ feh --version
feh version 3.4-1-gc9e024d-dirty
Compile-time switches: curl exif verscmp xinerama 

$ ls -l test_feh.jpg 
-rw-rw-r-- 1 real real 4742039 Mai 29 18:55 test_feh.jpg

$ feh --edit test_feh.jpg 
```
Type "<" then quit

```
$ ls -l test_feh.jpg 
-rw-rw-r-- 1 real real 604261 Mai 29 18:55 test_feh.jpg
```
Result: Size massively shrinked and exif data are lost. Seems something other than jpegtran is used here to rotate the image?

**Comment by reald** [comment]
Maybe this is the problem: gib_imlib_image_format(w->im) returns "jpg" but 
(!strcmp(gib_imlib_image_format(w->im), "jpeg") in imblib.c tests against "jpeg". (Ubuntu 20.04)

**Comment by derf** [comment]
Oh dear. Yep, that's an issue introduced by Imlib2 1.6 switching from "jpeg" to "jpg". It affects anyone using a recent Imlib2 version.

I'll publish a bugfix release shortly, thanks for pointing it out!
