### ISSUE TITLE
feh goes to the next image after an action is performed

### ISSUE THREAD

**Issue by Dupond** [derf/feh#533]
Hello,

I use the following wrapper for feh (`/usr/local/bin/feh`):

```
#!/bin/bash
/usr/bin/feh --auto-rotate --edit --scale-down --title "%n (%wx%h, %S - zoom %z) - feh [%u/%l]" --thumb-title "%n (%wx%h, %S - zoom %z) - feh" -A 'filetype=$(file -b --mime-type %F) && xclip -selection clipboard -t $filetype -i %F' "$@"
```

The action works fine: hitting "0" copies the image to the clipboard. But if feh loads an image list (e.g. starting feh with `feh images/*`), then hitting "0" also goes to the next image.

Is this an expected behaviour, or a bug? Or (very possible) a bug from my own code? Thought I should report it, just in case ;)

Best regards !

**Comment by derf** [comment]
Hi!

This is expected and documented behaviour. Prefixing your action with a semicolon (`... -A ';filetype=...'`) will make feh reload the image instead of advancing to the next one. As a reload has no effect when the image has not been changed, this should work for your use case.

**Comment by Dupond** [comment]
Oh sorry, I've missed that in the man page (which I have read several times though...) I see it now.
Thank you very much for the detailed explanation !
