### ISSUE TITLE
Reload does nothing in thumbnail mode?

### ISSUE THREAD

**Issue by deliciouslytyped** [derf/feh#545]
If I open a directory with `feh -t -R 1`, adding files to it later doesn't refresh the view: new images don't appear.

**Comment by derf** [comment]
Hi!

Indeed. The documentation fails to mention that feh's reload options only apply to slideshow mode. thumbnail/index mode is too much of a hack to easily support (filelist) reloading at the moment, but I'll make sure to update the documentation to reflect this. Thanks for pointing it out!

**Comment by deliciouslytyped** [comment]
Thanks. I was hoping it could be made to work. Oh well. :( I suppose I can try to do something with inotify.
