### ISSUE TITLE
Feature request: Trigger more than one action by key press

### ISSUE THREAD

**Issue by griai** [derf/feh#547]
Currently, feh allows to bind only one action to a key. If the same key is also used for another action we are up for undefined behavior, as the manual says. For certain tasks, however, it would be preferable to have more than one action bound to one key. For example, I have the use case that I want to trigger a certain action immediately when the next image is shown (e.g. by pressing rightarrow).
This would necessitate to invert the current mapping in the key config file, which currently is like that
    action --> key1 key2 ...
to a mapping that binds actions to certain keys:
    key --> action1 action2 ...

**Comment by derf** [comment]
Hi!

If you always want to execute an action when loading an image, you can abuse `--info`. The info command is executed whenever an image is loaded (but also when zooming or panning it, so be aware of that).

More fine-grained actions or key bindings are not planned at the moment, sorry.
