### ISSUE TITLE
Is there any argument to exclude directories with `--recursive`

### ISSUE THREAD

**Issue by chhajedji** [derf/feh#550]
Is there any way to use `feh` over a git repo. Issue arrises with argument `--recursive` and it tries to look files inside `.git` directory. Hackish solution could be to move .git to some other place when version control is not needed and bring it back when modifying/adding files.

**Comment by derf** [comment]
Hi!

That's not possible. feh, like most programs, also looks into dotfiles such as `.git` when running in recursive mode. However, you can work around it with other shell commands.

If only the base directory contains a `.git` directory, you can use shell globbing to only pass non-dotfiles to feh:

```
feh --resursive *
```

or

```
feh --resurcive /some/directory/*
```

For a generic solution, you can use find:

```
feh $(find -type d -not -path '*/\.*')
```

The `--recursive` option is not needed in this case.

**Comment by chhajedji** [comment]
Thanks, this helps.

**Comment by chhajedji** [comment]
Thanks, this helps 🙂

--

Regards,
Chinmay Chhajed
________________________________
