### ISSUE TITLE
Feature Request: Use imagemagick's convert to set background images not supported by imlib2

### ISSUE THREAD

**Issue by notevenaperson** [derf/feh#552]
Feh already uses the imagemagick's convert to view images not supported by imlib2. The background setter feature can't use the convert binary, and because of that doesn't support the same wide number of formats Feh is able to display. As a user, it's unexpected that it can't set as background image formats it is able to display.

**Comment by derf** [comment]
Which version of feh are you using and how are you invoking it? It works fine here:

```
feh --conversion-timeout 30 --bg-center some_file.svg
feh --conversion-timeout 30 --bg-center some_file.pdf
```

It also works from the right-click menu when loading the image without `--bg-center`, and also works for other background setting options.

**Comment by notevenaperson** [comment]
My mistake, it does work if I pass `--conversion-timeout` as an option. I've been using a wrapper for Feh with that option set for a long time, and forgot that option has to be passed to enable this feature, and is not something Feh does automatically.
