### ISSUE TITLE
feh v3.5, --info displays "Failed to run info command" after a few days

### ISSUE THREAD

**Issue by hawgcaller** [derf/feh#564]
I am running feh v3.5 on a RaspberryPi 3B+ as a digital photo frame.  Everything works great for a few days but then for some reason the --info option becomes problematic.

I've built feh with the following options: curl=0 xinerama=0 verscmp=1 exif=1

The photo files are streamed from a cifs share mounted as /home/pi/slideshow.  In addition to displaying the photos I want to display the photo date from EXIF data.  I'm using --info and exif to extract the date field and display it.  The call to feh is made from a shell script which runs on boot.  Here are the contents of that script file:

```
#!/bin/bash
/usr/local/bin/feh \
--quiet \
--recursive \
--hide-pointer \
--randomize \
--fullscreen \
--slideshow-delay 10 \
--fontpath /usr/share/fonts/truetype/dejavu/ \
--font DejaVuSans/20 \
--zoom max \
--auto-rotate \
--info "exif %F -tDateTimeOriginal | grep Value | sed 's/Value: //' | sed 's/:/-/' | sed 's/:/-/' | date -f - +%D" \
/home/pi/slideshow &
```

As I stated above this works well for two or three days then suddenly in place of the date value the string "Failed to run info command" is displayed.  All subsequent photos display this error rather than the date.  In addition to using exif to extract the DateTimeOriginal field I've also used exiftool in another shell script (--info calls the shell script rather than exiftool directly) and experienced the same issue.

A quick look through the source code reveals that this error is generated in the feh_draw_info() function in imlib.c when info_pipe cannot be opened.  I piped the output of feh to a file and do not see any errors related to info_pipe.

Is this error the result of a mistake on my part?  Am I somehow compiling are calling feh incorrectly?  What can cause info_pipe to fail to open?

**Comment by derf** [comment]
You already referenced it in #553, but just to be safe: Could you check whether d473ac13e7b70e8ad7a009a0f8c6d793934d03f1 resolves this issue as well?

**Comment by hawgcaller** [comment]
Daniel,

I'd be happy to check it out, but of course it will take several days to
test.  I'm not experienced with pulling a bugfix release in linux.  How do
I do that?  I currently use the procedure posted on finalrewind.org to
download and install the official releases: *wget
https://feh.finalrewind.org/feh-3.6.tar.bz2
<https://feh.finalrewind.org/feh-3.6.tar.bz2>*

-phil

**Comment by derf** [comment]
Great! I'll publish the bugfix release later today or tomorrow, so you can just wait until feh 3.6.1 becomas available. Or, if you prefer, you can test the git version which already contains the fixes.

For the latter, install git on your raspberry pi, and then run

```
git clone https://github.com/derf/feh.git
cd feh
```

from there on, it's the same steps as with the .tar.bz2 file.

**Comment by hawgcaller** [comment]
Thanks. I expected that was all that was needed but I wanted to ask to make
sure.

-phil

**Comment by derf** [comment]
And it's good that you did. There's a lot of software out there where building from git is more involved than building from a release tarball and requires additional steps.

**Comment by hawgcaller** [comment]
I've pulled the git repository onto my Raspberry Pi and built it.  Build
version is 3.6-4g04d2f10.  I looked at the source code for slideshow.c and
it contains the new code which removed EXIF cache.  It looks like make
doesn't install with exif=1, so I'm trying to find the compile options in
the Makefile to turn that on.

-phil

**Comment by hawgcaller** [comment]
Please ignore my last email. I realized I need to call exif=1 from make and
not modify Makefile.  Looking at the output of make, I think I successfully
built with exif=1 curl=0 xinerama=0 and verscmp=1 but running feh --version
reports that cull xinerama and verscmp switches were enabled at compile
time so I don't know why that is happening.

I've rebooted and the feh slideshow is running.  I'll monitor the
memory usage with top until you release 3.6.1 to see if the memory grows.

-phil

**Comment by hawgcaller** [comment]
I've been running 3.6.1 for seven days without memory overruns or the "Failed to run info command" error.  This doesn't prove that the problem has been resolved by the changes in 3.6.1, but feh is running without issue longer than it has in the past.  I'll continue to monitor it for the next week and report back.

**Comment by hawgcaller** [comment]
feh has been running for 14 days now on 3.6.1 without any memory overflow or "Failed to run info command" errors.  I am satisfied that the updates in 3.6.1 have resolved this issue.  derf, you can close this issue now, or if you'd prefer I'll close it.

**Comment by derf** [comment]
Glad to hear and thank you for testing. I also consider the issue to be resolved now.
