### ISSUE TITLE
[Feature] Ability to exit feh on mouse move

### ISSUE THREAD

**Issue by GLLM** [derf/feh#568]
Hi all,

I'm using .sh script which acts like a screensaver (starts when nothing happens on the computer) ... it displays photo from a selection of folder, fullscreen, not menu, no right-click ... 
just the title line at the bottom center and a few exif/iptc info on the bottom left !
It works great !!

But this "screensaver" is lacking one feature : exit when I move the mouse.
Could this be added to feh, or am I asking something that should be managed outside feh?

If it's not up to Feh to managed this, and you know how to do it, by all means, please tell ! (Kubuntu 20.10 here) ... I never was able to have (on linux) something act close to MS Windows screensaver.

Many thanks,
Have a good we.
Gllm

**Comment by Luz** [comment]
I do not think this should be an issue for feh.

You could use these commands to construct a script:
xdotool -> to get mouse position and therefore detect mouse movement
kill -> to exit feh

**Comment by GLLM** [comment]
Hi @Luz 
Thanks for your reply.
I was not seeing it as a bug/issue but rather as a feature. No problem for not acknowledging it :)
I'll try investigate the suggested solution
Thanks
GLLM

**Comment by derf** [comment]
You can now bind the special mouse button "0" to actions such as quit; this should be precisely what you're looking for.

`echo "quit 0" >> ~/.config/feh/buttons` will cause any feh instance to quit as soon as the cursor is moved. If you want CLI instances to behave normally and only xscreensaver feh instances to quit on mouse movement, you can use a different buttons config for xscreensaver instances by setting the `XDG_CONFIG_HOME` engironment variable appropriately. It defaults to `~/.config`.

**Comment by GLLM** [comment]
Hi @derf
Thanks for your message.
I 'git clone' the repo to reinstall it (following the guidelines on the site) and tried with your proposition (I had to create  ~/.config/feh/buttons which did not exist beforehand) ... , but I cant get the mouse to produce any effect.

I use Ubuntu 21.10, have a intel core i7 7700k + 32GB RAM + NVidia GTX 1070 (X11)

Not sure waht I'm doing wrong ... 
Shall I add a parameter to the command line so that the mouse buttons are read ?

Many thanks
G.
