### ISSUE TITLE
How to configure keyboard panning?

### ISSUE THREAD

**Issue by SeanPedersen** [derf/feh#573]
Hey I managed to configure, mouse wheel scrolling using:

feh/buttons
```
# Unbind existing scroll operations
prev_img
next_img
# Set <action> <mouse button>
zoom_in 4
zoom_out 5
```

Now I am wondering how to configure image panning (currently only works by dragging the mouse) using keyboard (in my case WASD). Anyone got a clue?

**Comment by derf** [comment]
Hi!

Sorry for the late reply. To pan the image using your keyboard, you need to re-bind `scroll_left` and similar in `.config/feh/keys`.
