### ISSUE TITLE
Action save_filelist does not use directory from --output-dir

### ISSUE THREAD

**Issue by pepa65** [derf/feh#577]
In spite of what it says in the `Changelog` for release v3.1 (`Respect -j / --output-dir when using save_image or save_filelist actions.`) the action `save_filelist` does not use the directory specified on `--output-dir`.

It seems the fix is in `src/filelist.c` to change the line `tmpname = feh_unique_filename("", "filelist");` into:
```
char *base_dir = "";
if (opt.output_dir) {
  base_dir = estrjoin("", opt.output_dir, "/", NULL);
}
tmpname = feh_unique_filename(base_dir, "filelist");
```
(as in the analogous code in `src/slideshow.c` for `save_image`).

**Comment by derf** [comment]
Indeed. This is an error in the changelog; `save_filelist` never supported `--output-dir`. It should, though, so I'll fix that.
