### ISSUE TITLE
Support for heic images

### ISSUE THREAD

**Issue by overdetermined** [derf/feh#579]
I have some heic images which were taken with a Samsung S7 (I believe iPhones also use this format) and was not able to view them with feh (version 3.6.1 on archlinux).

I get the following WARNING:
 `Does not look like an image (magic bytes missing)`

I tried compiling the following "extension" https://github.com/vi/imlib2-heic  and copying the lib into the path:
 `/usr/lib/imlib2/loaders`... Perhaps I have made a mistake here, perhaps I am using the wrong OS, but it seems to me feh does not support *.heic and I am wondering if this will change in the future.

Thanks.

**Comment by derf** [comment]
Hi!

Due to a [performance issue in Imlib2](https://phab.enlightenment.org/T8739), feh hardcodes the set of supported file formats. You can set the environment variable FEH_SKIP_MAGIC to override this check, e.g. `FEH_SKIP_MAGIC=1 feh ...`.

Could you check whether that works for you? If it does, I'll include heic in feh's file format check so that it works with imlib2-heic out of the box, without the need to set environment variables first.

**Comment by overdetermined** [comment]
Thank you for the prompt reply! Yes, setting this environment variable solves this problem for me. Thank you very much. Do you know if heic images will be supported out of the box at any point?

**Comment by derf** [comment]
IMHO It'd make sense for upstream imlib2 to support HEIC/HEIF images in the long run, but I don't know if the Imlib2 developers share that opinion.

Anyways, I have added heic images to feh's check of supported file formats, so you should be able to use imlib2-heic without setting `FEH_SKIP_MAGIC=1` now. And if Imlib2 upstream starts supporting heic, so wil feh.

**Comment by dllud** [comment]
Indeed, with phone vendors now adopting HEIF, support should be upstream at imlib2.
I've opened an issue about it at their bug tracker: https://phab.enlightenment.org/T8877

**Comment by sarmong** [comment]
@derf , support for heic has been added to the imlib2. 

Probably, it is still not working for me because the binary is prebuilt with an old version of the lib in the Arch repo. 

Can you please realease a new version of feh with support for imlib2?
