### ISSUE TITLE
default parameter for open image (config file)

### ISSUE THREAD

**Issue by drazde** [derf/feh#582]
Hi, 
Is it possible to specify a default parameter set when an image is opened?

I use feh for open image from nautilus (or other graphical file managers), and I would like always scale the immage by default.

**Comment by derf** [comment]
Hi!

Yes, that's possible. Write "feh --whatever --default --options --you --want" to ~/.config/feh/themes

See https://man.finalrewind.org/1/feh/ "-T, --theme" and "THEMES CONFIG SYNTAX" for details.

**Comment by drazde** [comment]
I open an image by filling the window and show the exif information by default 

With only this config _~/.config/feh/themes_
`feh --scale-down --draw-exif`

It's amazing! 
Thanks!.
I didn't think it was that easy. I didn't underestand the meaning of _themes_ config files sorry
