### ISSUE TITLE
Failure to open files with non-latin characters from PCManFM

### ISSUE THREAD

**Issue by lockie** [derf/feh#584]
Hello!
I have feh set as default image viewer, and sometimes when double clicking on images in PCManFM, feh wasn't starting at all. I've launched PCManFM from command line to find out that there are problems with files containing non-lating characters in their path, for instance, clicking on an image located in directory `/tmp/тест` gives me
```
feh --start-at 'file:///tmp/%D1%82%D0%B5%D1%81%D1%82/ragetrollface.jpg'
feh WARNING: /tmp/%D1%82%D0%B5%D1%81%D1%82 does not exist - skipping
feh: No loadable images specified.
See 'man feh' for detailed usage information
```
Should I report this problem to PCManFM bugtracker too perhaps? Other image viewers (viewnior at least) do not appear to have this problem.

**Comment by derf** [comment]
It works fine when pcmanfm calls `feh 'file:///tmp/...'` (without --start-at), so this is likely a feh bug.

**Comment by derf** [comment]
feh didn't handle url-encoded path components in this case. It does now, thanks for reporting it.

**Comment by lockie** [comment]
Awesome! You're welcome :)
