### ISSUE TITLE
How to exit slideshow using touch monitor?

### ISSUE THREAD

**Issue by tazar117** [derf/feh#585]
Hi! In my project I'm using feh to display slideshows on touch monitor. The problem is that I don't know how to close slideshow as my RPi doesn't want to detect right-click gesture from touchscreen. Is there a way to add "esc" button on the slideshow screen? Adding simple "x" in the corner would make things a lot easier for me, but I'm not sure if it's even possible.
If not, what can I do to workaround this problem? Maybe somehow "long tap" can be set as "exit"?

Thanks in advance.

**Comment by derf** [comment]
feh doesn't distinguish between short and long key presses and doesn't provide its own window manager elements. You can run feh in windowed mode and use the close button provided by your window manager, or you can make a regular mouse button press (i.e., short tap) quit feh by writing the following to `~/.config/feh/buttons`:

```
pan
quit 1
```

This will remove the button binding for pan (move an image around or advance to the next one, defaults to button 1) and bind mouse button 1 to quit instead.

**Comment by tazar117** [comment]
Thank you. It is the answer I expected, however I hoped to be surprised this time. I'll try to workaround it. Anyway, thanks for your answer.
