### ISSUE TITLE
Feature request: Open reddit galleries

### ISSUE THREAD

**Issue by pianoslum** [derf/feh#591]
Hi, thx for developing feh :)

Would it be possible to add support for reddit galleries, like https://www.reddit.com/gallery/l8baz8 ? I guess it's already capable to open imgur galleries...

**Comment by derf** [comment]
Hi!

feh is a simple image viewer without support for online galleries. It only supports URLs that lead directly to a single image, and not an HTML page. It doesn't have support for imgur either – there's always just one image per URL.

 Of course, if you come up with a program to download the gallery, extract the image URLs, and pass them to feh, it will happily display them ;)
