### ISSUE TITLE
Know which image is set by using --randomize option

### ISSUE THREAD

**Issue by chhajedji** [derf/feh#593]
I am setting wallpaper by `feh --recursive --randomize $HOME/Pictures/wallpapers/* --bg-scale` this command. I want to know which image is getting selected for wallpaper out of tons of images. How can I know that?

As an alternative I can select random image by piping all images to `shuf -n1` option and then set wallpaper using `feh`, but I don't want that.

**Comment by avlec** [comment]
It would be interesting to see what the maintainer thinks. I think this isn't very useful, as you can work around it with the method you suggested there. And this would introduce program output when normally there isn't any desired. As well as with Xinerama screens, outputting which image was used and the associated Xinerama index would be ambiguous in most cases.

But that aside you should be able to determine what file was used from ~/.fehbg as it will write the filenames as part of the script to generate the same desktop background. (see https://github.com/derf/feh/blob/master/src/wallpaper.c#L317)

**Comment by derf** [comment]
Precisely. I do not see a point of having feh output the file that ends up as wallpaper – if you need to know the which file from a randomized file list feh uses, you should randomize the list and select the file yourself.

You can indeed determine the file that was set from ~/.fehbg, as feh stores the command line needed to reproduce your current background there. The first file argument saved in the file is the background image on your first screen, and so on. Be aware that .fehbg will be quite large if your wallpaper directory contains many files.

**Comment by chhajedji** [comment]
Oh thanks. I can make use of `~/.fehbg` file. Wasn't aware of it.

**Comment by gustavobrangel** [comment]
I need the same thing as the OP does. However, I do not have this `~/.fehbg` file. Anything has changed since then?
