### ISSUE TITLE
Gets stuck in scroll loop when failing to read from stdin

### ISSUE THREAD

**Issue by robalni** [derf/feh#595]
If I put the program in the background and close the terminal I started it from in one command, feh gets stuck in an infinite scroll loop.

Steps:

```
$ feh image.png 
[1]+  Stopped                 feh image.png
$ bg; exit
```

Now if I look at the CPU usage while doing this I can see that it goes up when the terminal closes and stays at a high value. If I zoom in on the image, I can see that it automatically scrolls right.

For some reason this only happens if I do `bg` and `exit` in one command, not if I do one and then the other. I also need to press `^Z` to stop the program before I put it in the background. The bug doesn't happen if I start the program in the background using `&` at the end.

It seems that one reason this is happening is that we don't check for a 0 return value from the `read` function in the beginning of the `feh_event_handle_stdin` function, so if there is nothing to read on stdin, the program will act as if it got something and we will get a garbage value in `stdin_buf[0]`. The following change fixes the bug:

```diff
diff --git a/src/keyevents.c b/src/keyevents.c
index a5526a2..0ca489a 100644
--- a/src/keyevents.c
+++ b/src/keyevents.c
@@ -319,7 +319,7 @@ void feh_event_handle_stdin()
        char stdin_buf[2];
        static char is_esc = 0;
        KeySym keysym = NoSymbol;
-       if (read(STDIN_FILENO, &stdin_buf, 1) == -1) {
+       if (read(STDIN_FILENO, &stdin_buf, 1) <= 0) {
                control_via_stdin = 0;
                if (isatty(STDIN_FILENO) && getpgrp() == (tcgetpgrp(STDIN_FILENO))) {
                        weprintf("reading a command from stdin failed - disabling control via stdin");
```

The scrolling right behavior is a different bug (#596). This bug is only about treating no input as input.

**Comment by avlec** [comment]
Sounds like an appropriate patch for the bug you've discovered. Submit a pull-request.

**Comment by derf** [comment]
Thanks!
