### ISSUE TITLE
Scrolls right when reading control char from stdin

### ISSUE THREAD

**Issue by robalni** [derf/feh#596]
If I hold the ctrl key and press almost any letter or arrow key in the terminal that I started feh from, the program will interpret that as a scroll right command (as if I pressed ctrl-right). One effect of this is that I can't scroll in any other direction; if I press ctrl-left in the terminal it will still scroll right (but doing it in the X window still works correctly).

It seems that the reason this happens is that `feh_is_kp` is called for events that have not been initialized with any other value than zeros, so when we enter `feh_event_handle_generic` with the `state`, `keysym` and `button` parameters equal to 0, `feh_is_kp` will return 1 for all those events that have not been initialized, and `EVENT_scroll_right` happens to be the first of them (`EVENT_next_img` and `EVENT_prev_img` are initialized in `init_buttonbindings`):

```
	if (feh_is_kp(EVENT_next_img, state, keysym, button)) {
		if (opt.slideshow)
			slideshow_change_image(winwid, SLIDE_NEXT, 1);
		else if (winwid->type == WIN_TYPE_THUMBNAIL)
			feh_thumbnail_select_next(winwid, 1);
	}
	else if (feh_is_kp(EVENT_prev_img, state, keysym, button)) {
		if (opt.slideshow)
			slideshow_change_image(winwid, SLIDE_PREV, 1);
		else if (winwid->type == WIN_TYPE_THUMBNAIL)
			feh_thumbnail_select_prev(winwid, 1);
	}
	else if (feh_is_kp(EVENT_scroll_right, state, keysym, button)) {
		winwid->im_x -= opt.scroll_step;;
		winwidget_sanitise_offsets(winwid);
		winwidget_render_image(winwid, 0, 1);
	}
```

This bug happens both in xterm and xfce4-terminal and those are the only terminals I have tested it on.

**Comment by derf** [comment]
Handling the Control key without resorting to raw mode is tricky, since some keys are identical to Ctrl codes: pressing Tab is the same as Ctrl+I and Return/Enter is identical with Ctrl+M. I deliberately left out Ctrl support on stdin for this reason – but the current handling (with fallback to the first possible action) indeed isn't sensible.

I'll see if I can improve stdin support a bit and especially avoid unexpected behaviour for uninitialized data.

**Comment by robalni** [comment]
@derf I want to thank you for being so responsive and willing to fix issues. This is a better experience than I have had with most other projects I have reported issues to.
