### ISSUE TITLE
`--reload` with `--start-at` will add all images from where feh was launched instead of the specified directory

### ISSUE THREAD

**Issue by joelostblom** [derf/feh#597]
I noticed that the `--reload` flag is labeled as experimental in the docs, so this might be a known bug but I didn't see an issue for it. When I use `--reload` together with `--start-at`, feh it will put all images in the directory where feh was launched from into the filelist, even if the specified `--start-at` file is in a subdirectory.

As an example, if I do

```
feh --start-at dir/file.png -R 2
```

The initial filelist will consist only of those files inside `dir`, as desired. However, after two seconds, the reload will add all files in the parent of `dir` which is where the `feh` command was launched.

If I start feh with a directory `feh dir -R2`, the reload will work as expected and only add new files from `dir`.

**Comment by derf** [comment]
That was a new / unknown bug indeed. Thanks for pointing it out!

**Comment by joelostblom** [comment]
Thank you for the quick fix!
