### ISSUE TITLE
Feature request: setting caption size 

### ISSUE THREAD

**Issue by pietro14** [derf/feh#601]
I use feh for a slideshow on a large TV, but the captions are too small to be read. So, it could be useful to be able to set the size of captions, either by giving a new option to feh, or by writing this information in the caption files.

**Comment by derf** [comment]
Hi!

That's already possible using the -e / --font option, e.g. `feh --font yudit/50`. You can create a theme (see "THEMES CONFIG SYNTAX" in the feh manual) and have that option automatically applied when invoking feh using the theme.

**Comment by pietro14** [comment]
> Hi!
> 
> That's already possible using the -e / --font option, e.g. `feh --font yudit/50`. You can create a theme (see "THEMES CONFIG SYNTAX" in the feh manual) and have that option automatically applied when invoking feh using the theme.

Thanks! Is it possible to set the font color too?

**Comment by derf** [comment]
That's not supported, sorry

**Comment by HubKing** [comment]
Shouldn't it be able to be done within the GUI, not by command-line arguments?
