### ISSUE TITLE
Can't unbind mouse button 1 from next_img

### ISSUE THREAD

**Issue by stav** [derf/feh#604]
I have this in my `~/.config/feh/buttons`:

	prev_img
	next_img
	unbound 1
	reload_image 2
	zoom_in 4
	zoom_out 5

Zooming and reloading works fine with the mouse but every time I accidentally left-click the image it loads the next image and I loose all my formatting of the original image.

Is there a way to keep mouse button 1 from going to the next image?

I just built `feh`  from this repo:

    feh version 3.6.3-26-g9642354
    Compile-time switches: curl verscmp xinerama

**Comment by derf** [comment]
Hi!

The manual may be a bit unclear on that. By default, mouse button 1 is bound to "pan", i.e. advancing to the next image (click) or panning it (click and hold and move). This is different from the key binding `next_img`.

So, to unbind mouse button 1, your buttons config needs to contain the line

```
pan
```

This rnemoves the default binding (button 1) from the "pan" action.

**Comment by stav** [comment]
Yep, that was it.  Thanks @derf
