### ISSUE TITLE
Print image (to paper)

### ISSUE THREAD

**Issue by mb720** [derf/feh#613]
Hi and thanks a lot for feh!

In feh, is there a way to send the currently viewed image to a printer?

I can alternatively print the image using [`yad`](https://www.systutorials.com/docs/linux/man/1-yad/) or open the image in Firefox to get a print dialog.

**Comment by polvoazul** [comment]
its easy to do with a custom `--action`. you just call whatever printing program you want, passing the filename. Read the man for more info
