### ISSUE TITLE
fatal error: curl/curl.h: No such file or directory

### ISSUE THREAD

**Issue by thangta** [derf/feh#624]
I got an error when build feh on Xilinx petalinux (yocto)

fatal error: curl/curl.h: No such file or directory, Pls help
![image](https://user-images.githubusercontent.com/13417944/128357860-381c0b99-539d-4794-bafb-0a3e78f20d82.png)

**Comment by bittorf** [comment]
please install your distro specific package, e.g. libcurl-dev

**Comment by derf** [comment]
If that's not possible, you can also build feh without curl support: `make curl=0`
