### ISSUE TITLE
Question: Clicking Image In File Manger - How To Scroll Through Images?

### ISSUE THREAD

**Issue by 0pLuS0** [derf/feh#636]
Hello,

I'm running 3.7.2 I compiled from source in Slackware. 

I use SpaceFM as my file manager, when I click on an image in SpaceFM, the images appear in Feh, and I wanted to know, after clicking on an image, in a directory full of images, how I can scroll through these images?

Openbox is my desktop I use in Slack and I have a menu entry in Openbox I use for Feh to set wallpapers.

```command feh --scale-down --zoom fill -g 800x600 --title Feh "/home/foo/Wallpaper/"command```

With this menu option, when I launch Feh from the menu, the mouse wheel scrolls through all the images in the Wallpaper directory, as well as the left - right arrows.

If I run the command from a terminal the mouse wheel and left-right arrows also work;

```feh --scale-down --zoom fill -g 800x600 --title Feh /home/foo/Wallpaper```

I don't understand why I can't simply click on images in SpaceFM and the mouse wheel and left-right arrows won't continue to work?

I thought according to the man pages, in ~/.config/feh/buttons this should work for the mouse wheel? I still can't figure out the left-right arrows.

prev_img 4
next_img 5

THANKS

**Comment by 0pLuS0** [comment]
I fixed it!

/usr/share/applications/feh.desktop has the EXEC line as;
Exec=feh --start-at %u

So in /local/share/applications I made it like this;
Exec=feh --start-at %u --scale-down --zoom fill -g 1440x900

The -start-at %u does it matter where it's placed in that line?

THANKS

**Comment by derf** [comment]
Hi!

On Tue, Nov 16, 2021 at 04:54:53PM -0800, 0pLuS0 wrote:
> The -start-at %u does it matter where it's placed in that line?

Nope, you can place it wherever you want.
