### ISSUE TITLE
Enable support for drawing on top of other windows

### ISSUE THREAD

**Issue by Baitinq** [derf/feh#639]
It would be really cool if you could draw an image on another window (by window id) instead of the root window. That way feh could work with projects such as https://github.com/ujjwal96/xwinwrap.

**Comment by derf** [comment]
The `--window-id` option introduced in feh 3.7 should do precisely what you're looking for.
Note that it only accepts integer arguments; hexadecimal IDs aren't supported yet.

**Comment by Baitinq** [comment]
Oh, I think thats what the problem ive been having with xwinwrap, as it generates a window id in hexadecimal form. Do you know if this feature will be implemented soon?

**Comment by derf** [comment]
Right now :)

It was an easy-to-fix oversight in the --window-id implementation, so thanks for pointing it out.

**Comment by Baitinq** [comment]
Thank you!
