### ISSUE TITLE
imlib2 does not render certain SVGs

### ISSUE THREAD

**Issue by ATM-Jahid** [derf/feh#652]
`feh` cannot render some SVG images since the `1.8` release of `imlib2`.

For example, [this icon](https://github.com/johanmalm/jgmenu/blob/master/data/jgmenu.svg) used to work fine with `feh`, but now it does not.

I have downgraded `imlib2` to version `1.7.5`, and everything works fine with this version.

**Comment by N-R-K** [comment]
> imlib2 does not render certain SVGs

Are you sure this is an imlib2 issue? I can view the image fine with nsxiv on imlib2 git version. What `librsvg` version are you at?

**Comment by ATM-Jahid** [comment]
I didn't know about `librsvg`. I am using the version `2:2.54.0-2`.

The [related issue](https://github.com/johanmalm/jgmenu/issues/172) I opened in `johanmalm/jgmenu` got fixed with this [commit](https://github.com/johanmalm/jgmenu/commit/57f5e88257200253240f41eda7982983124eaf79).
