### ISSUE TITLE
Null pointer dereference caused by feh_event_handle_MotionNotify

### ISSUE THREAD

**Issue by juhakoir** [derf/feh#656]
There's a broken null pointer check at the end of function feh_event_handle_MotionNotify.
https://github.com/derf/feh/blob/cd02c0eacef0c080c2d62a097142cebbeaa0ba78/src/events.c#L682-L694

 If winwidget_get_from_window() returns NULL, feh_event_handle_generic() is called with a NULL winwid value, causing a segfault when accessing field winwid->caption_entry.
https://github.com/derf/feh/blob/cd02c0eacef0c080c2d62a097142cebbeaa0ba78/src/keyevents.c#L426-L429

The bug gets triggered when fullscreen mode is toggled during mouse movement.

**Comment by derf** [comment]
Indeed, thanks for pointing it out!
