### ISSUE TITLE
libcurl unable to retrieve the file while curl is able to

### ISSUE THREAD

**Issue by elig0n** [derf/feh#660]
trying to open an image from an https:// URL:

```
feh WARNING: open url: The requested URL returned error: 403

feh WARNING: https://URL/file.jpg - libcurl was unable to retrieve the file
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
```
even with `--insecure`.
but no problem whatsoever with `curl URL | feh -` (Response code 200)

version:
```
feh version 3.8
Compile-time switches: curl exif inotify help stat64 verscmp xinerama
```

the loaded library:
```
openat(AT_FDCWD, "/usr/lib/libcurl.so.4", O_RDONLY|O_CLOEXEC) = 3
```
```
/usr/lib/libcurl.so.4 -> libcurl.so.4.7.0
```
the library file is owned by 
```
usr/lib/libcurl.so.4.7.0 is owned by core/libcurl-compat 7.83.1-1 
```
and curl is:
```
curl 7.83.1-1
```
on Manjaro Linux 21.2.6

**Comment by derf** [comment]
I can't reproduce that here, with feh 3.8 and libcurl 7.83.1 on Debian Sid.

Could you recompile feh with `debug=1` and see whether `feh --debug https://...` indicates the source of the problem? In that case, libcurl debug output is enabled as well.

**Comment by elig0n** [comment]
I recompiled feh with debug=1 and then also with a [custom DEBUG function](https://curl.se/libcurl/c/debug.html)  and still could not find the source of the problem in the logs. Everything seems to be exactly the same (https scheme with HTTP/2) except the different response (403 vs 200).

Please try with this sample URL: https://img.pr0gramm.com/2022/06/12/8c418ce642994fe1.jpg

I managed to reproduce this same behavior with an older machine using feh 3.2.1, libcurl 7.58.0 (debian-based Linux Mint).

**Comment by derf** [comment]
curl sends HTTP requests with "User-Agent: curl/..." by default, whereas feh does not send a User-Agent header. Looks like that site is doing user agent-based allow-/denylisting, hence feh is unable to open the URL whereas curl is.

I'll think about adding a "feh/..." user-agent to requests originated by feh.
