### ISSUE TITLE
Button definition not working (as expected)

### ISSUE THREAD

**Issue by odinian** [derf/feh#661]
My goal is to redefine the buttons as below, this is in ~/.config/feh/buttons

```
# middle button
toggle_menu 2
# left mouse
prev_img 1
# right mouse
next_img 3
```
the problem is that the left and right mouse both advance to the next image. Do I have the syntax wrong? 

update: I see now that button 1 default to panning, which requires mouse movement. Is there any way to redefine a simple left click?

**Comment by derf** [comment]
The current button handling implementation is a bit sub-optimal in that it does not automatically un-bind actions when they are redefined in .config/feh/buttons. You can resolve the issue by explicitly un-binding the pan action (i.e., specifying no binding).

```
pan
```

**Comment by odinian** [comment]
> The current button handling implementation is a bit sub-optimal in that it does not automatically un-bind actions when they are redefined in .config/feh/buttons. You can resolve the issue by explicitly un-binding the pan action (i.e., specifying no binding).

Thanks! This seems to work:

# middle button
toggle_menu 2
# left mouse
## unbind the default "pan" action from button 1
pan
# bind the new action
prev_img 1
# right mouse
next_img 3

**Comment by pepa65** [comment]
It would be really good in case of a binding that is assigned to an existing binding, that the old action is unbound autonatically!

**Comment by odinian** [comment]
> It would be really good in case of a binding that is assigned to an existing binding, that the old action is unbound autonatically!

A much easier solution would be to update the man page to note that if reusing a default button or key, need to "unbind"

**Comment by pepa65** [comment]
> A much easier solution would be to update the man page to note that if reusing a default button or key, need to "unbind"

Easier for the maintainers perhaps, but harder for the users. It is also not easy to find out what function name a key is currently bound to. Ideally, the softtware should take care of this.
