### ISSUE TITLE
Required dependency missing from list in README.md

### ISSUE THREAD

**Issue by ardnew** [derf/feh#665]
## Summary, steps to reproduce
- Trying to build `feh` from source on Ubuntu 22.04 LTS
  - `master` (4e9788033709511a4e2dd94852777cfb216a4634)
- The following code block contains:
  1. The command I used to install all [listed required dependencies](https://github.com/derf/feh#dependencies)
  2. The command I used to build feh from source
  3. The resulting build error

```sh
# install all listed required dependencies
sudo apt install libimlib2-dev libcurl4-openssl-dev libpng-dev libx11-dev libxinerama-dev libexif-dev libexif12 libmagic-dev

# build feh from source
PREFIX=/opt/feh make curl=1 exif=1 help=1 inotify=1 magic=1 xinerama=1
...
cc -g -O2 -Wall -Wextra -pedantic -std=c11 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -D_DARWIN_C_SOURCE -DHAVE_LIBCURL -DINCLUDE_HELP -DHAVE_MKSTEMPS -DHAVE_LIBMAGIC -DHAVE_STRVERSCMP -DHAVE_LIBXINERAMA -DHAVE_LIBEXIF -DHAVE_INOTIFY -DPREFIX=\"/opt/feh\" -DPACKAGE=\"feh\" -DVERSION=\"3.9-3-g4e97880\"   -c -o main.o main.c
In file included from main.c:34:
wallpaper.h:31:10: fatal error: X11/Intrinsic.h: No such file or directory
   31 | #include <X11/Intrinsic.h>      /* Xlib, Xutil, Xresource, Xfuncproto */
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: main.o] Error 1
make[1]: Leaving directory '/opt/feh/src/src'
make: *** [Makefile:6: build-src] Error 2
```

## Workaround
After a quick search with `apt-file search "X11/Intrinsic.h"`, it appears this file is provided by apt package `libXt`.

I installed this package with `sudo apt install libxt-dev`, ran `make clean`, and then re-ran the same `make` command shown above. This time, `feh` built successfully.

## Suggested fix
Recommend adding `libXt` to the list of dependencies on the project's `README.md`.

**Comment by derf** [comment]
Indeed. Thanks for pointing it out!
