### ISSUE TITLE
Unable to show Paused state in info

### ISSUE THREAD

**Issue by amitksdev** [derf/feh#670]
When running feh in slideshow mode, I need to be able to show if the slideshow is manually Paused using the info (or any other mechanism) - it helps to know if the slideshow has been paused so that user knows not to expect the slideshow to move to next image.

**Comment by derf** [comment]
By default, feh only adjusts the window title. To get more information, e.g. via `--info`, you can use the `%a` format specifier. It returns either "playing" or "paused" depending on the slideshow state.
