### ISSUE TITLE
UTF-8 e-grave issue with option -K, caption path

### ISSUE THREAD

**Issue by step-** [derf/feh#675]
OS: GNU/Linux
feh version 3.9, Compile-time switches: curl exif inotify help magic verscmp xinerama

Command `feh -K caption ./feh.png` with caption text `« è »` saved to file `./caption/feh.png.txt` shows:

![feh-caption-20220921](https://user-images.githubusercontent.com/1414102/191526437-92727354-a096-423e-8def-bb2b1f641721.png)

The correct result would be a black rectangle with `« è »` as the caption.  Data files: [test-caption.tar.gz](https://github.com/derf/feh/files/9617366/test-caption.tar.gz).
The caption file is UTF-8 encoded.

**Comment by avlec** [comment]
Is feh defaulting to a font that doesn't have a display for those characters? Try using the `-e` option to specify a font

**Comment by step-** [comment]
Ah, right, it was using /usr/share/feh/fonts/yudit.ttf, which only includes the right double quote character. Fixed my configuration by adding line `feh --fontpath /usr/share/fonts/X11/TTF/ --font DejaVuSans/14` to `~/.config/feh/themes`.  Thanks.

**Comment by avlec** [comment]
Glad I could help :)
