### ISSUE TITLE
Please introduce an option for interpolation on resize

### ISSUE THREAD

**Issue by donaastor** [derf/feh#688]
Please introduce an option, in command or on a key, that allows me to change the method for interpolating for zooming in. When I zoom in too much I would like to see pixels sometimes, I don't want a "blurred" image. If we could pick the methods for anti-aliasing and interpolation it would be great.

**Comment by derf** [comment]
feh already provides the `--force-aliasing` flag that disables any kind of anti-aliasing / blurring and allows you to see individual pixels when zooming in. That seems to be what you're looking for.

**Comment by donaastor** [comment]
Yes!
Thank you, I didn't know the term aliasing also incorporates interpolation for zooming in...
