### ISSUE TITLE
Feature request: Variable display times in slideshow mode

### ISSUE THREAD

**Issue by 47tuc** [derf/feh#697]
I'm displaying images from multiple directories with a title image for each directory. I'd like to be able to show the title image for a shorter time than the rest of the images in the directory. Perhaps with a list of title images in a separate file.

**Comment by avlec** [comment]
This seems like a very niche use case. I doubt there'd be any development effort from people in this project.

I would however encourage you to undertakes this endeavour yourself as it would be an interesting problem to solve if you're keen on programming.

**Comment by derf** [comment]
This. I understand your use case, but think that it is too niche to warrant further complicating the already large amount of configuration options feh provides. I also don't have the time to implement or maintain it. So this is a wontfix, sorry.

You can, however, already solve this with a bit of scripting, e.g. by running feh without `--slideshow-delay` and using an external script that knows about the image that feh is currently displaying (e.g. via `--info "echo %F > $tmpfile"`) and passes SIGUSR1 ("next image") to feh after a suitable delay. I hope this helps.
