### ISSUE TITLE
missing yudit font (dependency documentation needed)

### ISSUE THREAD

**Issue by Tcll** [derf/feh#717]
```
feh WARNING: couldn't load font yudit/10, attempting to fall back to fixed.
feh WARNING: failed to even load fixed! Attempting to find any font.
feh ERROR: couldn't load menu font yudit/10, did you make install?
```

please add documentation for where users can obtain the yudit font if it should be missing like my case

**Comment by derf** [comment]
Hi!

The yudit font is shipped and installed with feh, so there is nothing to document.

If you built feh from source, you likely missed something during `make install`

If you installed feh using a package manager, the packager may have made a mistake.

At the moment, I don't see anything I can do about that, though I might be wrong. Feel free to re-open the issue if you have additional questions.

**Comment by Tcll** [comment]
I can't build from source

what I did was download the arch package and build an appimage

though I don't understand how the font isn't being detected from it's relative root if it's included

**Comment by Tcll** [comment]
I just checked the appimage, and `/usr/share/fonts/` is not included in the arch package

not sure where the problem is there
but I guess Arch packaged it wrong :P
