### ISSUE TITLE
Data loss with `--unloadable` deleting files

### ISSUE THREAD

**Issue by gwern** [derf/feh#741]
I was looking into how to get feh to automatically log or print out the last filename viewed, so I could more systematically go through my old photos without repeating\*, and I happened to see the example in the man page about verifying images like `feh --unloadable -r ~/Photos/`, which sounded useful: it would detect and print out potentially corrupt images.

I ran it, and to my surprise, feh deleted a bunch of my MP4 and other files. Leading aside the question of 'does this define unloadable as literally any file feh can't display as an image, even when their extension/fingerprint is not an image?', the deletion was a bad thing to do.

The deletion seems to be because in my default config, I define `--action "rm '%f'"` (to more easily get rid of redundant photos):

```Bash
$ feh --version
# feh version 3.3
# Compile-time switches: curl exif verscmp xinerama 
$ mkdir ./tmp/ && cd ./tmp/
$ touch foo.jpg
$ feh --action "rm '%f'"  ./
# feh WARNING: ./foo.jpg - No Imlib2 loader for that file format
# feh: No loadable images specified.
# See 'man feh' for detailed usage information
$ ls
# foo.jpg
$ feh --unloadable ./
# ./foo.jpg
$ ls
# foo.jpg
$ feh --action "rm '%f'" --unloadable ./
# ./foo.jpg
$ ls
$ 
```

Although I don't know why this is the case, because according to the Feh man page, the only thing `--unloadable` should be doing to files is "Just print out their names" and it should be very safe to run and not cause data loss:

     -u, --unloadable
             Don't display images.  Just print out their names if imlib2 can NOT successfully load them.  Returns false if at least one image was loadable.

No mention is made by the man page of executing any actions, and feh does not do so when called without `--unloadable`. 

Nor does this seem like desirable behavior to just run actions by default on all matching filenames - after all, since they are just being printed out, one can run any action or command one wants on them or feed them into a pipeline.

\* I haven't figured this out yet

**Comment by derf** [comment]
This is intended behaviour, but was only documented alongside `--action` so far. I have added a note about this to `--loadable` and `--unloadable`.

I hope that you were able to recover all lost data.
