### ISSUE TITLE
Feature request: Get last file path viewed when exiting feh

### ISSUE THREAD

**Issue by KiLLeRRaT** [derf/feh#757]
It'd be pretty cool to be able to get the path to the last filename that was viewed when exiting feh.

My use case would be to use feh as a sort of image selector, where I can launch feh with 5 images, go through these and select an image, and quit.  My script will then have the path to the file that I selected and continue.

Do you know of any way that this could be done?

**Comment by derf** [comment]
You can use something along the lines of  `--action 'echo %F > /tmp/feh-marked-file'`. Then you can press enter to mark a file, quit feh, and retrieve the marked file from within your script. You could also call your script directly via `--action`.

Alternatively, you can use `--info 'echo %F > /tmp/feh-last-viewed-file'`. This way, when quitting feh, the last viewed filename will always be present in said file.
