### ISSUE TITLE
[Feature Request] Slideshow - Add auto-pan to slideshow

### ISSUE THREAD

**Issue by ribbal** [derf/feh#761]
When an image aspect ratio does not match the aspect ration of the display screen, currently it is displayed:
- with black bars which doesn't take advantage of the full screen (e.g. portrait image displayed on landscape display)
- zoomed in with the edges of the image cropped, which results in parts of the image being lost

I would like to see a 'pan' option where the image is zoomed in, and it pans slowly up or down (or sideways) to display the whole image whilst taking advantage of the whole display.

I envisage an additional option such as `--zoom pan`. Also, I would suggest having a `pan-duration` option to set how long the pan process should take (e.g. 5 seconds).

(I've seen this on other slideshow programs, and I think it looks great!)

**Comment by derf** [comment]
Hi!

I agree that such a feature would be useful for slideshow setups. However, feh is mostly an image viewer – at the moment, I consider auto-panning to be out of scope.
