### ISSUE TITLE
zoom, scale-down etc. are a huge mess

### ISSUE THREAD

**Issue by derf** [derf/feh#81]
- when using feh --scale-down, the middle button toggles between zoom 100% and zoom to fit. It should only set zoom to 100%
- --scale-down: removing the zoom = 1.001 workaround from keyevents.c, zoom 100% -> zoom in / out breaks
- same for events.c, except there's no workaround in place

**Comment by ulteq** [comment]
I think this can be closed.

**Comment by derf** [comment]
Fixed by applying #364 and some others. Thanks a lot :)
