### ISSUE TITLE
EXIF orientation tag does not influence the displayed image orientation

### ISSUE THREAD

**Issue by soulpatrol** [derf/feh#86]
feh version: 2.4

My Panasonic TZ5 camera produces the following orientation-related EXIF tags for a portrait image 
(retreived by exiftool -a -u -g1 image.jpg):
IFD0:Orientation=Rotate 270 CW 
IFD1:Orientation=Rotate 270 CW
Panasonic:Rotation=Rotate 270 CW
However feh displays these images in landscape orientation, which is incorrect.

On the other hand, Canon 20D sets the following tags:
IFD0:Orientation=Horizontal (normal)
Canon:AutoRotate=Rotate 270 CW
and surprisingly, feh displays this image in portrait orientation.

**Comment by asalamon74** [comment]
Is this feature still on the todo list? An exif based autorotate would be a really good feature.

**Comment by Konfekt** [comment]
:+1:

**Comment by ashwin** [comment]
:+1:

**Comment by Maeda1** [comment]
:+1:

**Comment by shane-axiom** [comment]
In case anyone lands here looking for the correct option, recent versions of feh accept the `--auto-rotate` flag. I think this issue can probably be closed.

**Comment by nqzero** [comment]
using conversion with auto-rotate fails, eg `feh --conversion-timeout 1  --auto-rotate t2.raw`, ie it fails to rotate the displayed image. using `dcraw -c -T t2.raw | feh --auto-rotate -F -` works

displaying the exif-data (key: e) also fails with conversion
