### ISSUE TITLE
Missing RAW image capability

### ISSUE THREAD

**Issue by ghost** [derf/feh#89]
When trying to load an image (example file: _dsc0419.arw) provided by my camera (Sony SLT-A55V), feh throws an TIFF error and exits.

Background: before i develop images in RawTherapee I used to use a regular image viewer for quick preview without needing to start up a heavy RAW processing tool. With feh this is not possible any longer. The Image viewer i used before I switched to feh (Geeqie) could open such files by directly loading the embedded preview.

display (ImageMagick) invokes ufraw for creating a full sized version of the image for displaying (takes very long and produces kinda wrong results because of default settings are messed up), but maybe this could be a good approach?

What about having ufraw-batch as optional dependency and making feh able to process RAW images as if they were regular bitmap images? ufraw-batch command for extracting embedded image and write to stdout (btw. I didn’t find away making feh read from stdin!) is not as quick as Geeqie was, but feh could simply create a subprocess and get the results as input for displaying the image:

`ufraw-batch --embedded-image _dsc0419.arw --output=-`

Other information:

```
$ feh --version
feh version 2.5
Compile-time switches: curl exif xinerama

$ uname -rms
Linux 3.3.2-1-ARCH x86_64

$ file _dsc0419.arw
_dsc0419.arw: image/tiff

$ feh _dsc0419.arw 
TIFFReadDirectory: Warning, Unknown field with tag 50341 (0xc4a5) encountered.
MissingRequired: TIFF directory is missing required "ImageLength" field.
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
```

Example file (17 Megabytes):

http://u.0x7be.de/~dirk/_dsc0419.arw

**Comment by gavsiu** [comment]
This is the reason why I chose Geeqie. If feh supports raw/nef, I'd switch.

**Comment by glspisso** [comment]
Seconded. I use feh for most of my image working, and not being able to preview RAW files on it is a pain.

**Comment by xeverse** [comment]
Geeqie seems to be cool. Thanxx.
But the fehssue is still relevant i thinkk..

> This is the reason why I chose Geeqie

**Comment by Mindavi** [comment]
This can now be done by writing the output of `ufraw-batch --embedded-image _dsc0419.arw --output=-` to stdin and reading it with `feh -`.
